### ISSUE TITLE
Error on  Blazorise.Bar.OnLocationChanged

### ISSUE THREAD

**Issue by mortezabarzkar** [Megabit/Blazorise#2244] opened 2021-04-26 09:04 UTC
somtimes i got this error !! why ?

System.Threading.Tasks.TaskCanceledException: A task was canceled.

   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)

   at Blazorise.Bar.OnLocationChanged(Object sender, LocationChangedEventArgs args)

   at System.Threading.Tasks.Task.<>c.b__140_0(Object state)

   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)

**Comment by stsrki** [comment] 2021-04-26 09:08
Seems like something with navigations. OnLocationChanged is called when the URL changes. And it can trigger Bar Visible state, which in turn can call JSInterop.

Can you check when exactly it happens? It would help a lot to narrow it down.

**Comment by mortezabarzkar** [comment] 2021-04-26 10:39
in debug mode doesn't see it for now
but in publish mode some times it's happened and i do not know user what dose do

**Comment by stsrki** [comment] 2021-09-24 20:31
Closing since we were unable to reproduce the error.

**Closed by stsrki** 2021-09-24 20:31 UTC
