### ISSUE TITLE
Data grid row edit causes page to reload when enter is pressed and only one column is editable

### ISSUE THREAD

**Issue by mtbayley** [Megabit/Blazorise#3208] opened 2021-12-03 20:20 UTC
Same thing happens as with #3178 
If only one field is editable in a datagrid and enter is pressed, the entire page will reload.
![image](https://user-images.githubusercontent.com/34929316/144667741-edaf8fbc-eeea-4c6e-b84e-f9f865e9be3c.png)

**Comment by stsrki** [comment] 2021-12-03 22:01
This should be fixed with 0.9.5.1(current is 0.9.5.2). Can you try clearing the cache and see if it happens again?

@David-Moreira

**Comment by David-Moreira** [comment] 2021-12-03 22:06
hmm I think I only did query selector for inputs inside the thead, which should be the filter always. And what I did, was for disabling.
Rest should be working as it was previously? So it should actually be submitting the form instead of reloading? I suspect it might have to do with a submit button being present or not, I don't know if we took that into account when we developed it.
Eitherway I'll take a look.

**Comment by mtbayley** [comment] 2021-12-03 22:22
I can confirm that the 0.9.5.1 fix for datagrid filters works.
I would expect if the enter key is pressed, it will do nothing or submit the form. In my case I want it to do nothing.

**Comment by mtbayley** [comment] 2021-12-03 22:37
I actually want it to proceed to the next row (how II discovered this bug) - linking this enhancement here: #855 😉

**Comment by David-Moreira** [comment] 2021-12-03 23:19
If you don't want it to do anything, can you try setting SubmitFormOnEnter to false?

**Comment by David-Moreira** [comment] 2021-12-05 16:43
@mtbayley 
Can you provide the steps to reproduce?
I tried editting with 
`<DataGridCommandColumn TItem="Person"></DataGridCommandColumn>`
or
`dataGridRef.Edit(People.FirstOrDefault(x => x.Id == 1));`
and could not reproduce.

**Closed** 2021-12-13 14:24 UTC
Labels: Type: Bug 🐞, Status: Expecting Answer
