### ISSUE TITLE
DataGrid table is not displaying!

### ISSUE THREAD

**Issue by dkezri** [Megabit/Blazorise#2421] opened 2021-05-31 09:54 UTC
Hi!

I have the following Razor component:

```cshtml
 <div style="height:100px; width:500px">
    <DataGrid Data="models" Bordered Narrow />
</div>

@code {

    private ContractToDoModel[] models => new ContractToDoModel[]
            {
                new ContractToDoModel
                {
                    Behandler="Behandler",
                    Ansvarlig="Ansvarlig",
                    Yrkesgruppe="Lege",
                    Felt="Området",
                    MangelType="Mangel type"
                }
            };
}
```

The table is not displaying on my page. In my Bunit test i get the following  markup:

```html
<div style="height:100px; width:500px">
    <table id="0HM94302MPRAE" class="table table-bordered table-sm b-datagrid" blazor:ondrag="1" blazor:ondragend="2" blazor:ondragenter="3" blazor:ondragleave="4" blazor:ondragover="5" blazor:ondragstart="6" blazor:ondrop="7" blazor:elementReference="">
        <thead blazor:ondrag="8" blazor:ondragend="9" blazor:ondragenter="10" blazor:ondragleave="11" blazor:ondragover="12" blazor:ondragstart="13" blazor:ondrop="14">
            <tr blazor:onclick="22" blazor:ondrag="23" blazor:ondragend="24" blazor:ondragenter="25" blazor:ondragleave="26" blazor:ondragover="27" blazor:ondragstart="28" blazor:ondrop="29">

            </tr>
        </thead>
        <tbody blazor:ondrag="15" blazor:ondragend="16" blazor:ondragenter="17" blazor:ondragleave="18" blazor:ondragover="19" blazor:ondragstart="20" blazor:ondrop="21">
            <tr class="table-row-selectable" blazor:onclick="30" blazor:ondrag="31" blazor:ondragend="32" blazor:ondragenter="33" blazor:ondragleave="34" blazor:ondragover="35" blazor:ondragstart="36" blazor:ondrop="37">

            </tr>
        </tbody>
    </table>
</div>
```

Regards
Diko

**Comment by stsrki** [comment] 2021-05-31 10:00
You only defined the DataGrid component. and you have to define have all the columns. See an example https://blazorise.com/docs/extensions/datagrid/#basic-example

We have plans to make it work as you tried. Without specifying the columns it would pick them from the model. But the feature is still in the planning stage.

**Comment by dkezri** [comment] 2021-05-31 10:01
Thanks @stsrki  for replying me.

**Comment by stsrki** [comment] 2021-05-31 10:15
No problem. I will close it now since the issue is answered :)

**Closed by stsrki** 2021-05-31 10:15 UTC
