### ISSUE TITLE
Autocomplete : Investigate NotFound Handling with SearchChanged as a long-running task

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#2996] opened 2021-10-05 15:23 UTC
Also long-running tasks in eventcallbacks like `SearchChanged` (e.g. this is being done in ABP lookups) are also currently impacted by the respective changes. If the long-running task is being worked on and Autocomplete gets re-rendered during this time, `NotFoundVisible` will be `true` and the `NotFoundContent` will be shown even though the `NotFound` event callback will never be invoked.

_Originally posted by @MichalCadecky in https://github.com/Megabit/Blazorise/issues/2879#issuecomment-934429775_

**Comment by stsrki** [comment] 2022-04-03 19:18
Is this still an issue?

**Comment by David-Moreira** [comment] 2022-04-03 23:35
Haven't investigated yet. Other priorities in the meantime and no other complaints like this from other users so far.

**Comment by stsrki** [comment] 2022-04-04 08:30
Should we close it then?

**Comment by MichalCadecky** [comment] 2022-04-04 08:44
The thing is - the approach to use `SearchChanged` callback to fetch and filter data from remote server is mostly used in ABP but the template for generating Autocompletes/Lookups for related entities does not utilize the `NotFoundContent`. I am not sure if anyone else is using same idea, because there is separate issue regarding the remote data retrieval support for Autocomplete.

Yes, it is just a visual glitch. But I don't agree with closing it.

Anyway, it should be very easy to reproduce. Just add some `await Task.Delay` to `SearchChanged` handler and see how the `NotFoundContent` will be rendered meanwhile the delay is performed (obviously you have to modify the bound item list so before the delay it does not contain the item/any item and add it after the delay).

**Closed** 2022-07-03 13:01 UTC
Labels: Status: Investigate, Type: Possible Bug, Area: Autocomplete, Status : Finished
