### ISSUE TITLE
Time Picker does not fire associated event when time is 'picked' in 0.9.3.8

### ISSUE THREAD

**Issue by bh4017** [Megabit/Blazorise#2481] opened 2021-06-16 09:05 UTC
**Describe the bug**
This is really a continuation of issue [2437](https://github.com/Megabit/Blazorise/issues/2437#issuecomment-860699275) which I have found to be partially fixed in 0.9.3.8 but there is a remaining issue with it as follows:

Using a TimePicker set up as follows:

`<TimeEdit TValue="TimeSpan?" Time="@selectedStartTime" TimeChanged="@OnStartTimeChanged" />`

And then an associated handler as follows:

`private void OnStartTimeChanged(TimeSpan? time)
{
      selectedStartTime = time;
}`

The handler is not triggered when a time is manually picked from the picker.

However, it is possible in 0.9.3.8 to assign a time to the picker by assigning to the bound variable and this time is reflected on the picker:

`selectedStartTime = new TimeSpan((DateTime.Now.Hour - 1), 0, 0);`

As with the associated problems in 0.9.3.7, I can get around it by downgrading to 0.9.3.6.

**To Reproduce**
This is described in the issue itself but there is also an example program which demonstrates the problem here:

https://1drv.ms/u/s!AsgXPGP9HrtQiL0Z-6igugP4gOEktg?e=xfQJjw

**Expected behavior**
Picking a time should trigger the associated event handler.

https://1drv.ms/u/s!AsgXPGP9HrtQiL0Z-6igugP4gOEktg?e=xfQJjw

**Comment by stsrki** [comment] 2021-06-16 09:08
Thank you for the detailed explanation. The issue is a duplicate of #2462 and it is already being fixed. Since it was practically only a single reported bug I wanted to wait a little more before to see if there will be more issues before releasing a new patch. I will probably release it today.

**Closed by stsrki** 2021-06-16 09:08 UTC
