### ISSUE TITLE
Saving DataGrid State

### ISSUE THREAD

**Issue by christosvorkas** [Megabit/Blazorise#4925] opened 2023-08-11 07:02 UTC
I am using the DataGrid component on a blazor server app I'm developing. I present the datagrid and when the user clicks on an entry, I navigate to a new page showing details for the selected entry (typical list -> detail scenario).

When the user returns back to the list (grid) screen, I want to show the grid exactly as it was when he clicked the entry. For this, I save the "current state" of the grid, being the pagesize, page, the current sorting (which I get by tapping into the SortChanged property of the grid), and I also want to preserve the FILTER that is currently applied (on all the columns).

The "columns" property of the grid is protected and I cannot access it to get the current "searchValue" property of each column.

NEW FEATURE:
**Is it possible to expose the "columns" property so we can have access to it?
or even better, could new "SaveSate()" and "RestoreState()" methods be introduced to save/restore all the states of the grid (column order (in addition to sorting), visibility, width etc, in addition to the pagesize, page, sorting, filtering that I currently need to preserve?**

Thanks!

**Comment by David-Moreira** [comment] 2023-08-11 16:18
Hello @christosvorkas this is a duplicate of #4651 we do plan to add state management on a future version.

For now you would have to manually bind to the available eventcallbacks or bound parameters and save the state.

The columns will be available on the next version **v1.3**, which is scheduled to come out very soon.
![image](https://github.com/Megabit/Blazorise/assets/22283161/29dd4d41-e51e-4e99-bae3-3464787ca022)

I'm going ahead and going to close this issue. But feel free to reopen it if you feel like there's anything that hasn't been answered correctly.

**Closed by David-Moreira** 2023-08-11 16:18 UTC
Labels: Type: Feature ⚙
