### ISSUE TITLE
NumericEdit cannot disable numeric stepping from keyboard up/down

### ISSUE THREAD

**Issue by sgesweinFusion** [Megabit/Blazorise#2316] opened 2021-05-07 18:23 UTC
NumericEdit fields change values when the up and down arrows are pressed. This is a painful surprise to some end users working with a column of NumericEdits, who may the try the arrow keys for navigation because of reflexes learned from Excel.

Attempts to disable this behavior with Step="0" and Step="any" are not effective. 

1. Using Blazorise 0.9.3.5 or earlier, go to a NumericEdit (with no Step set) and the value 10.
2. Press the up arrow.
3. Value changes to 11.

**Expected behavior**
Users expect no change to the value input.

**Additional context**
Pointing users at [HTML5 spec explanations](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) for this behavior is not really a solution anyone is enjoying. 

Binding a TextEdit to a decimal value is not trivially satisfactory either. 

This is being used in a project with a "no JS, C# only" coding guideline, so JS workarounds like you'd find in a [StackOverflow discussion](https://stackoverflow.com/questions/30869720/is-it-possible-to-disable-step-in-input-type-number) aren't a good fit either.

Ideally, a Blazorise NumericEdit would have an EnableStep attribute that would, when set to false, prevent any stepping arrows from appearing and any keyboard use from triggering the HTML5 step behavior.

Per https://github.com/stsrki/Blazorise/issues/2292 I understand that NumericEdit changes are coming soon - any chance for this change?

**Comment by stsrki** [comment] 2021-05-08 20:22
At first, I thought the issue is fixed with https://github.com/stsrki/Blazorise/pull/2222 but then I had to re-read your issue and realize you mean it should not be able to change the numeric value if `Step` is not defined. I don't think that is the right behavior. As far as I know, if the `step `is not defined on regular `input type="number"` the `step` is by default equal 1, and you can still change it with up and down key. Same thing with NumericEdit.

I will need to think it through. Maybe EnableStep parameter makes sense in this case.

**Comment by sgesweinFusion** [comment] 2021-05-10 12:18
I think you're understanding what I'm looking for - I'm envisioning `EnableStep="true"` being the default and leaving `input type="number` working according to the HTML spec, and `EnableStep="false"` disabling everything associated with the spin button features in that spec that surprise my users so badly.

**Comment by stsrki** [comment] 2021-05-10 12:23
Having `type="number"` is not possible at this time simply because it is too limited regarding the customization and formating. For example, you cannot change the display format, and you cannot change the decimal separator or the number of decimals. It is fully in control by the browser and the user system settings.

Only by doing a separate component that is based in `type="number"` instead of` type="text"`. Like `TrueNumericEdit`, or something... :)

**Closed** 2021-06-29 10:24 UTC
Labels: Type: Feature ⚙
