### ISSUE TITLE
DatePicker displayed below all content

### ISSUE THREAD

**Issue by Moskus** [Megabit/Blazorise#4818] opened 2023-06-14 08:07 UTC
**Describe the bug**
The DatePicker is shown below all content on the page when clicked.

**To Reproduce**
Create a new Blazor Project, add Blazorise (and all dependencies as described on the [Quick Start](https://blazorise.com/docs/start) page), add [DatePicker](https://blazorise.com/docs/components/date-picker) to a page, and scroll down below the content after the DatePicker is clicked.

**Expected behavior**
I expect the DatePicker to be displayed on top of the content as it does on the demo page.

**Screenshots**
![image](https://github.com/Megabit/Blazorise/assets/320826/582eb180-fa5f-42de-9941-c29625f5f82d)

**Comment by reubenalfred** [comment] 2023-06-24 04:00
I had the same issue and I checked if all CSS framework provider related libraries were in place.

Once fixed that everything worked fine.

Also checked in the _Host file to see if any local references are made to non existing paths, there were fixed that and bingo all gone!

**Comment by stsrki** [comment] 2023-06-24 06:51
The problem is related to a fixed static position of the picker menu. The issue is fixed in 1.3 with the introduction of the new API, but in the mean time, you try the following CSS as a workaround:

```css
.flatpickr-calendar.static {
    top: unset !important;
}
```

**Comment by Moskus** [comment] 2023-06-26 11:48
Perfect! This works!

The following CSS works for the time picker:
`.flatpickr-time.static {
    top: unset !important;
}`

**Closed** 2023-06-26 11:58 UTC
Labels: Type: Bug 🐞
