### ISSUE TITLE
Modal Service Feature

### ISSUE THREAD

**Issue by Fane276** [Megabit/Blazorise#3038] opened 2021-10-20 12:56 UTC
Hi there, 

I am looking for some modular, file separated alternative for modals. For the project I am working I need more modals for one page and I consider that the code become really hard to read/understand when writing modals directly in the page.

I propose and Modal Service, like Notification Service and Message Service,  whose methods to accept as parameters Blazor components for header, body and footer of the modal. Searching for a solution I had found that something like this is already implemented but unfortunately it does not work very good with Blazorise. You can check that solution to on [their repository](https://github.com/Blazored/Modal/tree/main)

Let me know how does this idea sounds for you.

**Comment by stsrki** [comment] 2021-10-29 19:46
Hi, this is a duplicate of #2986

Probably going to be worked on the next milestone.

**Closed by stsrki** 2021-10-29 19:46 UTC
