### ISSUE TITLE
[Bug]: Dropdown Item Checkbox does not always toggle on click

### ISSUE THREAD

**Issue by InzeNL** [Megabit/Blazorise#5486] opened 2024-05-03 08:45 UTC
### Blazorise Version

1.5.2

### What Blazorise provider are you running on?

Bootstrap4

### Link to minimal reproduction or a simple code snippet

https://github.com/InzeNL/DropdownCheckboxBug

### Steps to reproduce

* Run the application
* Click the "Dropdown Toggle"
* Click the area marked red in the image below. This is the area between the checkbox and the dropdown text, when the cursor is a pointer
![image](https://github.com/Megabit/Blazorise/assets/2505862/37d41ce9-1a77-4b6d-b412-b7829f4d2608)
* The checkbox does not get checked

### What is expected?

Clicking this area inbetween the checkbox should check the checkbox, as the entire rest of the area of the dropdown item does. The padding around the text and checkbox, the text, and the checkbox itself, all toggle the checkbox.

### What is actually happening?

The marked area is the only area that doesn't actually toggle the checkbox

### What browsers do you see the problem on?

Chrome, Microsoft Edge, Firefox, Brave

**Comment by David-Moreira** [comment] 2024-05-05 10:46
This happens on both bootstrap and bootstrap5. And also on the regular checkbox.

This does happen in the bootstrap5 framework itself
https://getbootstrap.com/docs/5.0/forms/checks-radios/#checks

While we could easily fix it by making the hidden checkbox input go a little wider to catch that blank space, I have to think, that maybe this is working as intended?
Or that it should be fixed by the css framework itself?
@stsrki thoughts?

---

@InzeNL 
As a workaround you can apply the fix yourself on your end try: 
```
.custom-checkbox .custom-control-input{
width: 1.5rem
}
```
That should make the hidden input grow wide enough for the click detection to go through
![image](https://github.com/Megabit/Blazorise/assets/22283161/b7811ef8-0013-4d7b-b952-f8a8ddd2f119)

**Comment by stsrki** [comment] 2024-05-05 11:52
I would rather that is behaves as per bootstrap documentation. It might be better to report it on their side and see if it is really a bug.

**Comment by David-Moreira** [comment] 2024-05-05 17:58
@InzeNL As we generally try not to make too many changes to the css framework unless we deem necessary would you be so kind to report this issue on bootstrap?
I'm going ahead and closing the issue. But feel free to reopen if you feel there's anything else in Blazorise side we can help you with regarding this matter.

**Closed by David-Moreira** 2024-05-05 17:58 UTC
Labels: Type: Bug 🐞
