### ISSUE TITLE
Modal is not closed when handling Closed event when Visible property is used

### ISSUE THREAD

**Issue by janseris** [Megabit/Blazorise#3491] opened 2022-02-21 20:36 UTC
**Describe the bug**
The modal does not always close, see below.
My assumption is that Closed event should fire just after modal is changed into closed state.

**Expected behavior**
Handling Closed event does not prevent dialog from being closed because the dialog should be closed at the moment of handling Closed event.

**Behavior**
- for all cases described below, e.Cancel in Closing is not set and thus the modal should always close:
1) Visible is used for initial value **_true_**
2) bind-Visible is used for initial value **_true_**

1a) when Closed is not handled:
  - modal **does not close using .Hide()** although it should because Closing event handler is triggered - not OK
  - modal closes using CloseButton with AutoClose=true and Closing event handler is triggered - OK

1b) when Closed is handled:
  - modal **does not close using .Hide()** although it should because Closing event handler is triggered - not OK
  - modal **does not close using CloseButton with AutoClose=true**  although it should because Closing event handler is triggered - not OK
  
-----------------------------------
- in both cases in 1b, Closed event handler is executed but the modal is not closed

---------------------------------------

2a) when Closed is not handled:
  - modal closes using CloseButton and using .Hide() - OK

2b) when Closed is handled:
  - modal closes using CloseButton and using .Hide() - OK

**Comment by stsrki** [comment] 2022-02-22 11:45
Do you have any code to reproduce the issue? 

Please be aware that when you have `<Modal Visible="true">` you have a one-way binding and you're practically saying to Blazor that it always set modal as visible, ie. opened.

**Comment by janseris** [comment] 2022-02-22 17:06
@stsrki yes and the code is in the issue - in the text file because github displays Blazor markup wrongly.
OK. Thanks. I am wondering why in the case that Visible=true, handling or not handling Closed event changes the behavior - when priting "closed" in Closed handler, the modal will close but then Closed is not handled, the modal will not close.

**Comment by stsrki** [comment] 2022-02-22 19:15
So, now it works for you, right?

It's basically because `Visible=true` is interfering with the internal Modal state on each render. Modal internally does something and then it receives some `Visible` value that is not in sync, every time Blazor re-renders part of the page.

**Comment by janseris** [comment] 2022-02-22 20:51
@stsrki 
The issue which I described persists.
The problem is not fixed.
I am using a workaround, but that does not fix the bug.

The issue is the following:




- Visible is used with initial value `true`

a) when Closed event is not handled:

    modal _**does not close**_ using` .Hide()` although it should because `Closing` event handler is triggered - not OK
    modal closes using `<CloseButton>` with `AutoClose=true` and `Closing` event handler is triggered - OK

b) when Closed event is handled:

    modal **_does not close_** using `.Hide()` although it should because `Closing` event handler is triggered - not OK
    modal **_does not close_** using `CloseButton` with `AutoClose=true` although it should because `Closing` event handler is triggered - not OK
    

The biggest surprise about this is that when Closed event is handled, the modal closes vs when Closed is not handled, the modal does not close. Handling the event should not affect the behavior of modal closing/not closing.

**Comment by stsrki** [comment] 2022-02-22 21:51
I'm trying with or without the `Closed` event and it works for me. To be able to reproduce it, and to fix it I will need to have the same code that you use for testing. Can you make it?

**Comment by stsrki** [comment] 2022-03-02 10:10
@janseris any news about the test project to reproduce the issue?

**Comment by David-Moreira** [comment] 2022-03-10 23:11
@janseris Friendly reminder. :)

**Comment by janseris** [comment] 2022-03-11 19:36
@stsrki @David-Moreira 
Hi, I have been on holidays and I have to work on a different project. 
Thus I will abandon the issue for now.
Thank you

**Comment by stsrki** [comment] 2022-03-12 07:25
Ok closing this issue. If you happen ta have the same problem later please open a new ticket.

**Closed by stsrki** 2022-03-12 07:25 UTC
Labels: Type: Bug 🐞
