### ISSUE TITLE
Carousel stop working

### ISSUE THREAD

**Issue by AlexTeixeira** [Megabit/Blazorise#2746] opened 2021-07-29 09:57 UTC
**Describe the bug**
Carousel stop working with version 0.9.4.1 bug working in 0.9.3.6

**To Reproduce**
Just implement documentation code

```cshtml
<Carousel @bind-SelectedSlide="@selectedSlide">
    <CarouselSlide Name="1">
        <Image Source="..." Text="City Skyline" Display="Display.Block" Style="width: 100%;" />
    </CarouselSlide>
    <CarouselSlide Name="2">
        <Image Source="..." Text="Coffee" Display="Display.Block" Style="width: 100%;" />
    </CarouselSlide>
    <CarouselSlide Name="3">
        <Image Source="..." Text="Mountain" Display="Display.Block" Style="width: 100%;" />
    </CarouselSlide>
</Carousel>
@code{
    private string selectedSlide = "2";
}
```

**Expected behavior**
To do not have the exception ( Have a look to Additional context )

**Additional context**

```Unhandled exception. System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Blazorise.Carousel.FindNextSlide(String slideName)
   at Blazorise.Carousel.OnTimerEvent(Object source, ElapsedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by stsrki** [comment] 2021-07-30 14:07
I have copy-pasted the same code and no error on my side.

**Comment by AlexTeixeira** [comment] 2021-08-04 11:02
Hi, 

Unable to repro with a fresh project... I will try to make the update in my project Friday and I come back to you :)

**Comment by stsrki** [comment] 2021-08-11 10:56
Hi, any luck with the repro project?

**Comment by stsrki** [comment] 2021-08-31 13:23
Closing since we could not reproduce the error.

**Closed by stsrki** 2021-08-31 13:23 UTC
Labels: Type: Possible Bug
