### ISSUE TITLE
Clicking on Autocomplete item throws NullReference Exception in .Net 6

### ISSUE THREAD

**Issue by solalem** [Megabit/Blazorise#3420] opened 2022-02-09 12:15 UTC
After I upgraded from .Net 5 to .Net6, all Autocomplete components are not working correctly. 

```
  <Autocomplete TItem="Category"
                TValue="Guid"                        
                Data="@Items"
                TextField="@((i)=>i.Name)"
                ValueField="@((i)=>i.Id)"
                @bind-SelectedValue="@_item.CategoryId"
                SearchChanged="(s) => LoadCategoryOptions(s)"
                Placeholder="Search Category...">
  </Autocomplete>               
```

The strange thing is that I can select options with keyboard keys and it displays the selected option correctly in the box. But, when I use a mouse to click and select, it throws exception.

**Expected behavior**
Clicking one of options given should show text in the text box.

** Error when mouse clicked **
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at <Namespace>.Products.Create.<BuildRenderTree>b__21_30(String s) in <Path>\Pages\Products\Create.razor:line 57
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Blazorise.Components.Autocomplete`2.<OnDropdownItemClicked>d__14[[DoneDeal.ViewModels.Operations.CategorySummary, DoneDeal.ViewModels, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Guid, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Blazorise.DropdownItem.ClickHandler()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by David-Moreira** [comment] 2022-02-10 00:37
I cannot figure out the error from that stack trace.
Can you please provide a repository replicating the issue? What blazorise version are you using?

What's in line 57?
`at <Namespace>.Products.Create.<BuildRenderTree>b__21_30(String s) in <Path>\Pages\Products\Create.razor:line 57`

**Comment by solalem** [comment] 2022-02-11 17:00
Hi @David-Moreira, it is the SearchChanged event handler. 
It calls this
```
        private async Task LoadCategoryOptions(String search)
        {
            Logger.LogInformation("Now loading CategoryOptions...");

            Items= await OperationsServices.CategoryService.ListAsync(search);
            StateHasChanged();
        }

```

**Comment by David-Moreira** [comment] 2022-02-11 21:12
Can you actually debug and let it throw the exception precisely where the error is?
That's probably easier. Post the image here if you can't figure out why that thing where its gonna throw is null.

**Comment by ivancavlek** [comment] 2022-02-15 09:01
Hi, @David-Moreira! 

I can confirm what @solalem wrote. I too have a problem by Autocomplete's SearchChanged.
It looks like that it is fired twice. Here's the complete workflow:

I have set the Autocomplete to fire after three letters have been entered.
After I write the first three letters, SearchChanged is fired, search parameter in SearchChanged correctly shows the three letters entered, the list of possible entries is shown and the first item on the list is selected - everything as intended.
Now, I select the first item on the list with the Enter button, SelectedValueChanged is fired and the selected parameter is correct, **BUT** at the same time SearchChanged is fired again with the search parameter as null or empty - I believe this is not intended.

My configuration is as follows:

```C#
@inherits TextSearchBase

<Autocomplete TItem="ContainerItemDto"
              TValue="string"
              Data="_repositoryContainerItems"
              DelayTextOnKeyPress="StoreApplicationUtility.DelayTextOnKeyPress"
              DelayTextOnKeyPressInterval="StoreApplicationUtility.DelayTextOnKeyPressInterval"
              Disabled="PickerIsDisabled"
              Filter="AutocompleteFilter.Contains"
              MinLength="StoreApplicationUtility.DelayTextMinLength"
              SearchChanged="OnSearchRepositoryContainerItems"
              SelectedValue="null"
              SelectedValueChanged="OnSelectRepositoryContainerItems"
              TextField="@(item => item.DisplayName)"
              ValueField="@(item => item.Id)">
    <NotFoundContent>@Localizer["Not found"]</NotFoundContent>
</Autocomplete>
```

```C#
private async Task OnSearchRepositoryContainerItems(string searchParameter)
{
   Console.WriteLine($"Bug - searchParameter - {searchParameter}");
    if (SearchParameterIsValid(searchParameter))
        _repositoryContainerItems = await SearchRepositoryContainerItemsFunction.Invoke(searchParameter);
}

private async Task OnSelectRepositoryContainerItems(string selectedRepositoryContainerItemId)
{
    var selectedRepositoryContainerItem = _repositoryContainerItems
        .Single(itm => itm.Id.Equals(selectedRepositoryContainerItemId, StringComparison.InvariantCulture));

    await OnContainerItemAdded.InvokeAsync(selectedRepositoryContainerItem);
}
```

**Comment by David-Moreira** [comment] 2022-02-15 13:27
I believe we may improve on that, gotta investigate if it makes sense or not. My guess is that it is being invoked with a `null` value, so your expression should expect `null` values like so:

```
              TextField="@(item => item?.DisplayName)"
              ValueField="@(item => item?.Id)"
```
Can you guys try this change?

**Comment by stsrki** [comment] 2022-02-15 14:11
Also, I think that `SearchChanged` is working fine. When you select the searched item, the search value should reset and that will trigger `SearchChanged` with the null value passed.

**Comment by ivancavlek** [comment] 2022-02-15 20:57
@stsrki, I have to disagree.

I have to set an unnecessary guard code because of the inner workings of a third party code that, IMO, is behaving unexpectedly. I expect that an event is raised if a user called for this event. If the component has to do internal cleaning, that's not something that a user initiated or of user's concern.
I received an error of unknown origin that took a lot of time to debug and furthermore, this isn't documented.

@David-Moreira, I still haven't tried the code, but it'll most likely work. Still, IMO, this is a hack and not a solution.

**Comment by stsrki** [comment] 2022-02-15 21:47
Let's say you have three values in the list.

- January
- February
- March

Now you start searching

1. write "F" "e" "b", which triggers `SearchChanged `every time for each letter.
2. dropdown menu shows
3. you click on "February" from the menu to select it
4. "February" gets selected and automatically shows in the input. `SelectedValueChanged` also gets triggered
5. `SearchChanged` gets triggered with null because you didn't search it(written in the search input) but selected the value from the menu.

**Comment by stsrki** [comment] 2022-02-16 09:37
I agree that `SearchChanged` should not be called if the `MinLength` condition is not satisfied. But when Autocomplete is switching from search mode into the selected mode I still think `SearchChanged` should be called with the null value because the search has ended. And you can easily check if the value is null or empty and ignore it.

**Comment by ivancavlek** [comment] 2022-02-16 10:01
I see that we agree that we disagree 😂.
My argument is still that this extra event shouldn't be fired at all.

Could we keep this bug/feature open if somebody else comes by and complains about the same things that I do? If no one else complains, then I'm definitely an exception and I'll accept that.

The _hack_ with null check that David presented works well and an additional guard code against nulls is needed in `SearchChanged` for now as a solution to an extra trigger event.

But the MinLength thing and documentation is definitely a bug.

**Comment by stsrki** [comment] 2022-02-16 10:09
We'll see how it goes 😅

Regarding the calling of:

```
TextField="@(item => item.DisplayName)"
ValueField="@(item => item.Id)"
```

with the item as a `null`. That part should be fixed. TextField and ValueField should only be accessed to get the item info and null is an invalid argument. @David-Moreira can you check this part?

**Comment by solalem** [comment] 2022-02-17 12:13
> I believe we may improve on that, gotta investigate if it makes sense or not. My guess is that it is being invoked with a `null` value, so your expression should expect `null` values like so:
> 
> ```
>               TextField="@(item => item?.DisplayName)"
>               ValueField="@(item => item?.Id)"
> ```
> 
> Can you guys try this change?

Yes that works. To add some idea here, I believe users should be put in a 'pit of success'. As a developer, I expected things to work with the default setup and I think don't need to care for edge cases like whether a library cares about nulls or not. I pulled lots of hairs in-part because the debugging experience was bad for blazor wasm. Thank you guys for the amazing library.

**Comment by David-Moreira** [comment] 2022-02-17 23:01
I'm actually not able to reproduce this. Could I request that one of you guys sets up a repro?

I tried this based on one of your examples:
Even our current examples don't check for null. 
```
<Autocomplete TItem="ContainerItemDto"
              TValue="string"
              Data="_repositoryContainerItems"
              Filter="AutocompleteFilter.Contains"
              MinLength="3"
              SearchChanged="OnSearchRepositoryContainerItems"
              SelectedValue="null"
              SelectedValueChanged="OnSelectRepositoryContainerItems"
              TextField="@(item => item.DisplayName)"
              ValueField="@(item => item.Id)">
    <NotFoundContent>Not Found</NotFoundContent>
</Autocomplete>
@code {

    public class ContainerItemDto
    {
        public string DisplayName { get; set; }

        public string Id { get; set; }
    }

    private List<ContainerItemDto> _repositoryContainerItems = new() { new() { DisplayName="David" }, new() { DisplayName = "TJ" } };
    private async Task OnSearchRepositoryContainerItems(string searchParameter)
    {
        Console.WriteLine($"Bug - searchParameter - {searchParameter}");
    }

    private async Task OnSelectRepositoryContainerItems(string selectedRepositoryContainerItemId)
    {
        Console.WriteLine($"Bug - OnSelectRepositoryContainerItems - {selectedRepositoryContainerItemId}");
        //var selectedRepositoryContainerItem = _repositoryContainerItems
        //    .Single(itm => itm.Id.Equals(selectedRepositoryContainerItemId, StringComparison.InvariantCulture));

        //await OnContainerItemAdded.InvokeAsync(selectedRepositoryContainerItem);
    }
}
```

**Comment by solalem** [comment] 2022-02-18 11:29
Sorry, I take my previous comment back. This is not the case of ```TextField="@(item => item?.DisplayName)"```. The problem is search parameter from SelectedChanged being null when an option is click-selected. After I added a null check before calling backend, the error is gone. This is inline with what @stsrki described before; search being invoked with a null string on click. Also, please remember, there is no issue if I selected an option using up and down arrow keys.

**Comment by David-Moreira** [comment] 2022-02-18 18:10
Ah so your both complaining about Search Changed being invoked with null and not the TextField/Value Field expressions.

I can see both sides... 

What do you say @stsrki do you maintain the same resolution?
We can leave the issue open as suggested.

**Comment by stsrki** [comment] 2022-02-18 18:32
Well, I still think SearchChanged should invoke with null after the item has been selected.

**Closed** 2022-03-08 13:40 UTC
Labels: Type: Bug 🐞, Status: Investigate
