### ISSUE TITLE
SelectList inside DataGrid closing Edit when selecting item

### ISSUE THREAD

**Issue by SynapsesConsortium** [Megabit/Blazorise#1033] opened 2020-06-26 19:50 UTC
**Describe the bug**
When I have a SelectList inside a DataGrid and I try to choose another value inside the SelectList, the edit gets canceled.
It might have something to do with the fact that the function I have inside the 'Data' parameter of the DataGrid gets called when I select a value inside the SelectList.

**Expected behavior**
```
<DataGrid TItem="TemplateLineTypeDataTransferObject"
          Data="OnLoad().Result"
          Editable="true"
          EditMode="DataGridEditMode.Inline"
          Filterable="true"
          Narrow="true"
          RowInserted="OnRowInserted"
          RowUpdated="OnRowUpdated"
          RowRemoved="OnRowRemoved"
          PageSize=999>
    <DataGridColumn TItem="TemplateLineTypeDataTransferObject" Field="@nameof(TemplateLineTypeDataTransferObject.FieldName)" Caption="Field Name" Editable="true" />
    <DataGridSelectColumn TItem="TemplateLineTypeDataTransferObject" Field="@nameof(TemplateLineTypeDataTransferObject.InputType)" Caption="Input Type" Editable="true">
        <EditTemplate>
            <SelectList Data="@LoadInputTypes()"
                        TextField="@((item)=>item.Value)"
                        ValueField="@((item)=>item.Key)"
                        SelectedValue="@((int)((CellEditContext)context).CellValue)"
                        SelectedValueChanged="@(e =>
                                    {
                                        context.CellValue = Convert.ToInt32(e);
                                        Console.WriteLine(context.CellValue);
                                    } )" />
        </EditTemplate>
    </DataGridSelectColumn>
    <DataGridColumn TItem="TemplateLineTypeDataTransferObject" Field="@nameof(TemplateLineTypeDataTransferObject.Regex)" Caption="Regex" Editable="true" />
    <DataGridCommandColumn TItem="TemplateLineTypeDataTransferObject">
        <NewCommandTemplate>
            <Button Color="Color.Success" Clicked="@context.Clicked">New</Button>
        </NewCommandTemplate>
        <EditCommandTemplate>
            <Button Color="Color.Primary" Clicked="@context.Clicked">Edit</Button>
        </EditCommandTemplate>
        <DeleteCommandTemplate>
            <Button Color="Color.Danger" Clicked="@context.Clicked">Delete</Button>
        </DeleteCommandTemplate>
        <SaveCommandTemplate>
            <Button Color="Color.Warning" Clicked="@context.Clicked">Save</Button>
        </SaveCommandTemplate>
        <CancelCommandTemplate>
            <Button Color="Color.Danger" Clicked="@context.Clicked">Cancel</Button>
        </CancelCommandTemplate>
    </DataGridCommandColumn>
</DataGrid>
```

```
@code {
    async Task<List<TemplateLineTypeDataTransferObject>> OnLoad()
    {
        var templateLineTypeService = ServiceProvider.GetRequiredService<TemplateLineTypeService>();

        var templateLineTypeDataTransferObjectList = await templateLineTypeService
            .GetAllAsync()
            .ConfigureAwait(false);

        return templateLineTypeDataTransferObjectList;
    }

    async Task OnRowInserted(SavedRowItem<TemplateLineTypeDataTransferObject, Dictionary<string, object>> insertedRowItem)
    {
        var templateLineTypeService = ServiceProvider.GetRequiredService<TemplateLineTypeService>();

        var templateLineTypeDataTransferObject = insertedRowItem.Item;

        await templateLineTypeService
            .CreateAsync(templateLineTypeDataTransferObject)
            .ConfigureAwait(false);
    }

    async Task OnRowUpdated(SavedRowItem<TemplateLineTypeDataTransferObject, Dictionary<string, object>> updatedRowItem)
    {
        var templateLineTypeService = ServiceProvider.GetRequiredService<TemplateLineTypeService>();

        var templateLineTypeDataTransferObject = updatedRowItem.Item;

        await templateLineTypeService
            .UpdateAsync(templateLineTypeDataTransferObject)
            .ConfigureAwait(false);
    }

    async Task OnRowRemoved(TemplateLineTypeDataTransferObject templateLineTypeDataTransferObject)
    {
        var templateLineTypeService = ServiceProvider.GetRequiredService<TemplateLineTypeService>();

        await templateLineTypeService
            .DeleteAsync(templateLineTypeDataTransferObject.Id)
            .ConfigureAwait(false);
    }

    List<KeyValuePair<int, string>> LoadInputTypes()
    {
        var inputTypes = Enum.GetValues(typeof(InputType))
               .Cast<InputType>()
               .Select(x => new KeyValuePair<int, string>((int)x, x.ToString()))
               .ToList();

        inputTypes.Insert(0, new KeyValuePair<int, string>());

        return inputTypes;
    }
}
```

**Screenshots**
![ezgif-3-4e93d93ae944](https://user-images.githubusercontent.com/38438495/85895476-b2e9fd00-b7ee-11ea-910f-88e7d368b0f6.gif)

**Comment by stsrki** [comment] 2020-06-26 19:52
That's strange. Can you show some code to reproduce it?

**Comment by SynapsesConsortium** [comment] 2020-06-26 19:54
> That's strange. Can you show some code to reproduce it?

I just added code samples to the initial post.

**Comment by SynapsesConsortium** [comment] 2020-06-29 16:40
@stsrki Were you able to replicate the bug?

**Comment by stsrki** [comment] 2020-06-29 16:44
Sorry, I was dealing with another issue and I still didn't touch this. Will try soon.

**Comment by SynapsesConsortium** [comment] 2020-07-14 08:43
@stsrki Any update on this?

**Comment by SynapsesConsortium** [comment] 2020-08-10 11:21
@stsrki Did you ever check this bug?

**Comment by adamhathcock** [comment] 2022-02-25 09:22
I'm running into this today with this exact same scenario.  No idea why the form closes.

**Comment by stsrki** [comment] 2022-02-25 10:09
This is an old issue so we need to reproduce it first. @adamhathcock what version you're using?

**Comment by adamhathcock** [comment] 2022-02-25 10:10
After reading https://github.com/Megabit/Blazorise/issues/3149

I'm thinking the select list closing might cause focus to be lost then it decides to hide the form.

I just updated to 0.9.5.6 and see the same thing.

My razor is
```
<DataGridSelectColumn TItem="ActivityTemplateItem" Field="@nameof(ActivityTemplateItem.Type)" Caption="Type" Editable="true">
    <DisplayTemplate>
                    @context.Type.ToString()
    </DisplayTemplate>
<EditTemplate>
    <Select   TValue="ActivityType"
            SelectedValue="@((ActivityType)context.CellValue)"
            SelectedValueChanged="@((v) => { context.UpdateCell("Type", v); })"
            Disabled="context.Item.Id != Guid.Empty">
        @foreach (ActivityType type in Enum.GetValues(typeof(ActivityType)))
        {
            <SelectItem TValue="ActivityType" Value="@type">@type.ToString()</SelectItem>
        }
    </Select>
</EditTemplate>
</DataGridSelectColumn>
```

I was typing this as i saw you reply!

**Comment by adamhathcock** [comment] 2022-02-25 10:11
my razor is more messy than it used to be but that's me trying different values or functions seeing what would change behavior

**Comment by stsrki** [comment] 2022-02-25 10:15
You're missing `context.CellValue = v;`

Eg. `SelectedValueChanged="@((v) => { context.CellValue = v; context.UpdateCell("Type", v); })"`

**Comment by adamhathcock** [comment] 2022-02-25 10:33
I had the line like you said and it was the same behavior: the edit dialog/form closed

**Comment by adamhathcock** [comment] 2022-02-25 11:18
```
<DataGridColumn TItem="ActivityTemplateItem" Field="@nameof(ActivityTemplateItem.Type)" Caption="Type" Editable="true">
    <EditTemplate>
        <Select TValue="ActivityType"
                SelectedValue="@((ActivityType)context.CellValue)"
                SelectedValueChanged="@((v) => context.CellValue = v)">
            @foreach (ActivityType type in Enum.GetValues(typeof(ActivityType)))
            {
                <SelectItem TValue="ActivityType" Value="@type">@type.ToString()</SelectItem>
            }
        </Select>
    </EditTemplate>
</DataGridColumn>
```

Same behavior

**Comment by stsrki** [comment] 2022-02-25 11:20
@David-Moreira wanna have a look at this?

**Comment by adamhathcock** [comment] 2022-02-25 11:53
Just some more information:  it seems any EditTemplate being used and the widget inside losing focus will cause the form to be hidden again.  I used a textedit (as a workaround for this enum issue) and providing the edit template does the same thing.  I click int the text box, add a character, then click away.   The form hides.

```
 <DataGridColumn TItem="ActivityTemplateItem" Field="@nameof(ActivityTemplateItem.Name)" Caption="Name" Editable="true">
    <EditTemplate>
        <Validation Validator="args => CheckEnum<ActivityType>(args)">
            <TextEdit Text="@((string)context.CellValue)" TextChanged="value => context.CellValue = value">
                <Feedback>
                    <ValidationError/>
                </Feedback>
            </TextEdit>
        </Validation>
    </EditTemplate>
</DataGridColumn>
```

**Comment by stsrki** [comment] 2022-04-03 17:23
Closing the ticket since we're still unable to reproduce it on our side.

**Closed by stsrki** 2022-04-03 17:23 UTC
Labels: Type: Possible Bug
