### ISSUE TITLE
[DataGrid] ExpandoObject / dynamic data source

### ISSUE THREAD

**Issue by JohnLamontagne** [Megabit/Blazorise#548] opened 2020-01-30 19:53 UTC
I am trying to build a DataGrid from an arbitrary dataset that is unknown prior to runtime. I load this data from a CSV, which specifies the fields that exist in the dataset alongside the values. I then create a ExpandoObject and store it in a dynamic field contained within my DataRow class, which is what I actually pass to the DataGrid. The DataGrid is then told to access fields within the dynamic object stored in DataRow.

Here is the code for the DataGrid itself:
```
<DataGrid TItem="DataRow"
                      Data="@dataSource"
                      Filterable="true"
                      TotalItems="@dataSource.Count"
                      ShowPager="true"
                      PageSize="15"
                      PageChanged="OnPageChanged"
                      @bind-SelectedRow="@selectedRow"
                      @ref="dataGrid">
                @foreach (var fieldName in dataSource.FieldNames)
                {
                    string fieldPath = nameof(DataRow.ObjectRepresentation) + "." + fieldName;
                    <DataGridColumn TItem="DataRow" Field="@fieldPath" Caption="@fieldName" Sortable="true" />
                }
</DataGrid>
```

This is how ObjectRepresentation is declared in DataRow:
`public dynamic ObjectRepresentation;`

Note here that DataRow.ObjectRepresentation is the ExpandoObject that I create dynamically with properties as defined by the CSV header.

For example, if I have the following CSV:
```
id,name,location
0,John,Florida
```

ObjectRepresentation will contain three fields:
id, name, and location. 

This fails because at some point in your library the dynamic object (ObjectRepresentation) is accessed as a System.Object, which will not allow the underlying dynamic properties to be accessed. This occurs in the FunctionCompiler method GetSafeField, with the specific exception being a System.ArgumentException.

**Describe the solution you'd like**
Some mechanism to allow feeding in a dataset that is not known until run-time.

**Comment by stsrki** [comment] 2020-01-30 21:18
Not sure but try with this.

```diff
<DataGrid 
+    TItem="DataRow.ObjectRepresentation"
    Data="@dataSource"
    Filterable="true"
    TotalItems="@dataSource.Count"
    ShowPager="true"
    PageSize="15"
    PageChanged="OnPageChanged"
    @bind-SelectedRow="@selectedRow"
    @ref="dataGrid">
    @foreach ( var fieldName in dataSource.FieldNames )
    {
+        // you only need the name of a field in the TItem object, not the entire path
        <DataGridColumn TItem="DataRow" Field="@fieldName" Caption="@fieldName" Sortable="true" />
    }
</DataGrid>
```

PS. I believe @tonjurah can help you with this better. He was having the same problem a few days ago and I think he has solved it.

**Comment by stsrki** [comment] 2020-01-30 21:21
FYI. You don't need `TotalItems` unless you load data manually by using the event handler `ReadData`.

**Comment by JohnLamontagne** [comment] 2020-01-31 14:03
`<DataGridColumn TItem="DataRow.ObjectRepresentation" Field="@fieldName" Caption="@fieldName" Sortable="true" />`

Does not work as TItem wants a Type, not a reference to the actual in-memory object. ObjectRepresentation is dynamic field referencing an ExpandoObject. If I instead pass in `typeof(DataRow.ObjectRepresentation)` the compiler freaks out, as you can't pass around dynamic in generics like that.

It makes me very hopeful that someone else has had this issue and solved it though. I'm going to tinker with the DataGrid source today and see whether I can't derive whatever their solution was in the meantime.

**Comment by tonjurah** [comment] 2020-01-31 15:30
I can try to help but I need some more information first:
What is your dataSource and Row defined as? One thing that worked, at least as far as compiling goes, is to make DataRow it's own class and put that in the TItem of the DataGridColumn. I had to make my DataGrid into a generic component that takes in it's own TItem, which is inferred from another parameter defined as:
`IEnumerable<TItem> CurrentTable`
The TItem then, should be your Row class, if I'm following correctly, and you can iterate over the values in a Dynamic object by the answer here: 
https://stackoverflow.com/questions/19139417/how-to-dynamically-get-a-property-by-name-from-a-c-sharp-expandoobject

I know that's probably not 100% what you are looking for but I think I could help you work out something.

**Comment by stsrki** [comment] 2020-01-31 15:49
@tonjurah Thanks for taking time to answer the question.

And for off-topic: https://webapps.stackexchange.com/questions/123808/github-whats-this-pro-tag-on-my-profile

**Comment by JohnLamontagne** [comment] 2020-01-31 16:21
`public class DataRow
    {
        private Dictionary<string, DataField> _fields;

        public DataField LatField { get; set; }

        public DataField LonField { get; set; }

        public DataField PrimaryField { get; set; }

        /// <summary>
        /// Provides an object representation containing the fields in this DataRow.
        /// </summary>
        public dynamic ObjectRepresentation;

        /// <summary>
        /// Number of columns in this row
        /// </summary>
        public int Count { get => _fields.Count; }

        public DataField this[string name]
        {
            get
            {
                return _fields[name];
            }
        }

        public DataRow(string[] fieldNames)
        {
            _fields = new Dictionary<string, DataField>();

            foreach (var fieldName in fieldNames)
            {
                var dataField = new DataField(fieldName);
                dataField.ValueChanged += DataField_ValueChanged;

                _fields.Add(fieldName, dataField);
            }

            object person = new { Lol = "" };
            
           
            this.UpdateObjectRepresentation();
        }

        private void UpdateObjectRepresentation()
        {
            this.ObjectRepresentation = new ExpandoObject();

            foreach (var fieldName in _fields.Keys)
            {
                ((IDictionary<String, object>)this.ObjectRepresentation)[fieldName] = _fields[fieldName].GetValue();
            }
        }

        private void DataField_ValueChanged(object sender, System.EventArgs e)
        {
            this.UpdateObjectRepresentation();
        }
    }`

This is DataRow. As you can see, it contains a dictionary of DataField. This is simply a class that contains an identifier (what the field is called) and the actual value of the field. A dictionary is needed because we do not know how many DataFields there will be until the user loads a CSV file. 

This is also the class where the ObjectRepresentation field is stored. This contains all of the DataFields that exist in the _fields dictionary, but rather than items in the dictionary they are stored as fields in the (dynamic) ExpandoObject. 

The DataSource class simply contains a list of all the DataRows.

**Comment by tonjurah** [comment] 2020-01-31 18:13
Is it possible for you to create an example project of this for me? I'm at work so I unfortunately don't have much time to dedicate towards making one myself but I still want to try to help.

**Comment by stsrki** [comment] 2020-01-31 19:21
Test project would be great, We could help you more that way. Also I have some ideas for the future on how these kind of scenarios could be handled and the more use cases I have, the better.

**Comment by JohnLamontagne** [comment] 2020-01-31 20:49
Sure thing. I'll get an example project uploaded ASAP.

I hope it will also aid in expanding the capabilities of this library as you mentioned.

Thanks!

**Comment by JohnLamontagne** [comment] 2020-01-31 21:20
@tonjurah https://github.com/JohnLamontagne/DataGridBlazorTest

**Comment by tonjurah** [comment] 2020-02-03 19:03
@JohnLamontagne 
I was able to get it to render by doing the following:

```
<DataGridColumn TItem = "DataRow" Field = "@fieldPath" Caption = "@fieldName" Sortable = "true">
   <DisplayTemplate>
                @{
                    var eoAsDict = ((IDictionary<String, Object>)context.ObjectRepresentation);
                    @eoAsDict[fieldName]
                }
   </DisplayTemplate>
</DataGridColumn>
```

Basically all I did was add in a display template into it and use that to control what is being shown since the datagrid on its own cannot. Is that what you are looking for?

**Comment by JohnLamontagne** [comment] 2020-02-05 14:39
@tonjurah 

Yep, that appears to work fine for displaying. For the rest of the internal logic that is going on behind the scenes, it of course does not work due to the way the DataColumn relies on expressions. It would need to somehow support referencing the dynamic field without failing at the compile time check when it accesses the field as the primitive object base type.

**Comment by JohnLamontagne** [comment] 2020-02-05 16:15
I believe I have something working. I will fork the repo and implement this feature when I have more time to thoroughly test.

To support data item sources with dynamic fields, I included a new class to be used by DataGrid as well as modified the GetSafeField method. With this, you should be able to specify the field in your data as being dynamic / determined at runtime by using the DynamicSource to store these fields & as the Type passed into TItem for your grid & columns. You can then fill your DynamicSource objects with whatever unique fields you would like them to have. Now when FunctionCompiler creates an expression to return the field, it checks whether the TItem is DynamicSource (or whether the subfield you are specifying is). If it is, it gets the underlying value by invoking a special method in DynamicSource called GetProperty that returns the custom field you've stored in your DynamicSource object.

I apologize if any of this is confusing. Don't think I'm explaining this in the best way, but as I said I will fork, do a proper explanation, and then submit a pull request to see whether this would be a reasonable solution.

`private static Expression GetSafeField(Expression item, string fieldName)
        {
            var parts = fieldName.Split(new char[] { '.' }, 2);

            Expression field;
            if (item.Type.Equals(typeof(DynamicSource)))
            {
                field = Expression.Invoke(
                    DynamicExpressionParser.ParseLambda(new[] { (ParameterExpression)item }, typeof(object), $"item.GetProperty(\"{fieldName}\")"),
                    item);
            }
            else
            {
                field = Expression.PropertyOrField(item, parts[0]);
            }
            
            if (parts.Length > 1)
                field = GetSafeField(field, parts[1]);

            // if the value type cannot be null there's no reason to check it for null
            if (!IsNullable(field.Type))
                return field;

            // check if field is null
            return Expression.Condition(Expression.Equal(item, Expression.Constant(null)),
                Expression.Constant(null, field.Type),
                field);
        }`

`class DynamicSource : DynamicObject
    {
        Dictionary<string, object> _data
        = new Dictionary<string, object>();


        public DynamicSource()
        {
            _data = new Dictionary<string, object>();
        }

        public override bool TryGetMember(
        GetMemberBinder binder, out object result)
        {
            // Converting the property name to lowercase
            // so that property names become case-insensitive.
            string name = binder.Name.ToLower();

            // If the property name is found in a dictionary,
            // set the result parameter to the property value and return true.
            // Otherwise, return false.

            return _data.TryGetValue(name, out result);
        }

        // If you try to set a value of a property that is
        // not defined in the class, this method is called.
        public override bool TrySetMember(
            SetMemberBinder binder, object value)
        {
            // Converting the property name to lowercase
            // so that property names become case-insensitive.
            _data[binder.Name.ToLower()] = value;

            // You can always add a value to a dictionary,
            // so this method always returns true.
            return true;
        }

        public object GetProperty(string propertyName)
        {
            return _data[propertyName];
        }
    }`

**Comment by angelru** [comment] 2020-10-13 09:44
I am not sure that what is exposed here can solve my problem, any guidance? #1373

**Comment by kaivalagi** [comment] 2020-12-08 15:17
Currently at work we really want to use this blazorise library and the datagrid but we are facing the above issues with no support for dynamic/expando data sources. Could the above change to support a "Dynamic Source" or a similar solution allowing for dynamics be introduced into a release in the future? We can obviously fork the datagrid extension and edit as required but I think this would be a useful addition to your datagrid anyway?

**Comment by bh4017** [comment] 2021-05-19 15:24
I have a similar requirement in that I want to create a datagrid with columns that are to be determined at runtime.  I don't see a solution posted here.  John L was proposing a fix to Blazorise itself, the details for which I did not fully understand, but since this issue is still marked open I assume his pull request (if he ever submitted it) was not accepted.

In order to manage my expectations, do the maintainers of Blazorise expect to support datagrids with dynamic data sources in the near future?

**Comment by stsrki** [comment] 2021-05-19 15:47
Our friends at Volosoft have managed to do a dynamic grid. You can look at their example as an inspiration https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.BlazoriseUI/Components/AbpExtensibleDataGrid.razor

**Comment by bh4017** [comment] 2021-05-23 14:50
Thanks for the response @stsrki.

I had a look at the link you provided and first of all I decided to see if the given example would run.  If it runs, let's see if there's hope of it fulfilling my needs.

The first problem I had was getting it to compile.  I took actions to get it to compille, but it throws runtime exceptions.

Unfortunately I am not in a position to begin troubleshooting this body of code, especially as I've no idea who Volosoft are or what they're trying to do in this regard.

So I guess the answer to this question (for me) is: no, Blazorise does not support dynamic grids and I should not expect that support to be added in the foreseeable future.

Thanks again for your reply.

**Comment by stsrki** [comment] 2021-05-23 14:52
It will be done sometimes in the future, probably in 0.9.5 as that will be the last beta before 1.0.

**Comment by bh4017** [comment] 2021-05-24 18:23
Thanks @stsrki .  I took another look at the Volosoft example and I can't understand how it would work.  The issue is they've created a partial class to support their razor component, but that partial class has a <TItem> generic in it.  So when the class is instantiated this generic item must be determined.  And that's why the runtime exception occurs.

I guess there's a bigger picture behind all this that I simply don't understand.

Anyway, I will look forward to the 0.9.5 release where, perhaps, this functionality will be included in Blazorise :)

Thanks anyway for your efforts on this project much appreciated.

**Comment by Fabi** [comment] 2022-01-11 02:44
Any news?

**Comment by stsrki** [comment] 2022-04-03 17:16
DataGrid now supports columns without `Field` parameters. So I think it can be used to display end edit any data source if used with DisplayTemplate and EditTemplate. Since we don't have plans to add support for ExpandoObject by using a third-party system I think this is the best way.

Closing the ticket now.

**Closed by stsrki** 2022-04-03 17:16 UTC
Labels: Type: Discussion ☕
