### ISSUE TITLE
Error Loading Blazorise when selfhosting

### ISSUE THREAD

**Issue by samuelhurni** [Megabit/Blazorise#3324] opened 2022-01-14 11:58 UTC
**Describe the bug**
I did a Blazor WASM Project with Blazorise and want to Deploy the App at my Synology NAS in a docker Container with ngInx.

First of all, I deploy the app to a folder structure. There I start to test a python http server. Wen I run the application on localhost, I get an error while loading the staring page.
The error is:

`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Failed to fetch dynamically imported module: http://localhost:8000/_content/Blazorise/breakpoint.js?v=0.9.5.3
      TypeError: Failed to fetch dynamically imported module: http://localhost:8000/_content/Blazorise/breakpoint.js?v=0.9.5.3
Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: http://localhost:8000/_content/Blazorise/breakpoint.js?v=0.9.5.3
TypeError: Failed to fetch dynamically imported module: http://localhost:8000/_content/Blazorise/breakpoint.js?v=0.9.5.3
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__15`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Blazorise.Modules.JSBreakpointModule.RegisterBreakpoint(DotNetObjectReference`1 dotNetObjectRef, String elementId)
   at Blazorise.Bar.OnFirstAfterRenderAsync()
   at Blazorise.BaseComponent.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task )`

I did it also with an empty Blazor WASM Project and then there was no error for hosting the app localy with a python server.

**Comment by stsrki** [comment] 2022-01-14 12:05
We already had similar problems with JS modules: #3122, #3150

Can you see if any of the solutions in the posted issues can solve your problem? For example `.UseStaticFiles()`. usually works.

**Comment by David-Moreira** [comment] 2022-01-31 02:14
@samuelhurni 
Can you let us know if this helped? Or are you having a different issue then the one's reported? T
o me it seems that your web server should communicate a Mime type of js when delivering the requested resource, which would be server configuration. 

Let us know how it is going.

**Comment by samuelhurni** [comment] 2022-02-03 18:39
Hello

I haven't solved the issue because it was only with the python server a
problem. I deployed to a hosting with apache or ngnix servers and there
everything works fine.

Regards

Samuel

Am Mo., 31. Jan. 2022 um 03:14 Uhr schrieb David ***@***.***>:

**Comment by David-Moreira** [comment] 2022-02-03 23:12
Hello @samuelhurni 
So we can assume the problem is with the server configuration. May we close this issue. Or would you like to levae it open and eventually provide us with further details, see if we can help on the Blazorise's part somehow?

**Comment by samuelhurni** [comment] 2022-02-04 06:52
Was only a server config issue, with apache or ngnix no problem

**Closed** 2022-02-04 06:51 UTC
Labels: Type: Bug 🐞
