### ISSUE TITLE
Layout/Bar Header collapse issue in mobile

### ISSUE THREAD

**Issue by JaredMRomano** [Megabit/Blazorise#1615] opened 2020-12-16 20:44 UTC
**Describe the bug**
If you start the browser window as narrow as possible or on a mobile browser and you're using a layout with a header and a nested bar; when expanding the bar, instead of shfiting the contents below down and increasing height of the bar, it overlays just the menu items on top or below the contents below.

**To Reproduce**
On a desktop, go to the bootstrap demo page and make the window as narrow as possible.  Reload the page and toggle the header bar.  The bar never expands but the menu items still show up. You'll notice if you expand the width of the window larger then back to as narrow as possible, it will behave as expected.  unfortunately there is no way to do that in a mobile browser.

**Expected behavior**
The bar to expand to a height corresponding to the number of menu items and the contents below to shift down.

**Screenshots**
What happens:
![image](https://user-images.githubusercontent.com/10646171/102403880-243b8900-3fa4-11eb-8b50-1f40b849bf03.png)

What I expect:
![image](https://user-images.githubusercontent.com/10646171/102404062-682e8e00-3fa4-11eb-83e2-ec85417835b2.png)

**Additional context**

**Comment by stsrki** [comment] 2020-12-17 07:59
It's a bug indeed. Thank you for the report.

**Comment by Meberem** [comment] 2021-01-15 11:36
I started looking into this before I saw @MitchellNZ was working on this. It looks like it caused by [`if ( Mode != BarMode.Horizontal )`](https://github.com/stsrki/Blazorise/blob/master/Source/Blazorise/Bar.razor.cs#L59) but I am not sure on the implications of removing this, in my test branch it seems to perform fine, do you have any thoughts on this?

**Comment by David-Moreira** [comment] 2021-06-26 16:06
@stsrki / @MitchellNZ Can I take a look at this one?

**Comment by stsrki** [comment] 2021-06-26 20:28
@David-Moreira Fine by me. If I happen to start before you I will let you know.

**Comment by David-Moreira** [comment] 2021-06-27 09:38
Oh this might be fixed on the latest version.
I have tested it on my mobile, and on desktop, I am unable to reproduce.

@JaredMRomano could you take a look at https://bootstrapdemo.blazorise.com/ and see if this still happens?
@stsrki in case @JaredMRomano is unable to provide feedback, do you remember how you had reproduced this bug at the time? Can you also attempt to reproduce it on latest version?
![image](https://user-images.githubusercontent.com/22283161/123539814-74558e00-d733-11eb-8919-2ad76ed31e63.png)

**Comment by stsrki** [comment] 2021-06-27 10:56
I remember it was not working in one of my projects and then I might have fixed it. I cannot reproduce it now. Might be safe to close this ticket?

**Comment by David-Moreira** [comment] 2021-06-27 11:50
Seems like it.
Let's wait for a few days for OP to confirm. Otherwise we'll close on milestone completion.

**Comment by JaredMRomano** [comment] 2021-06-28 14:35
Everything is working on the demo and I checked my application which was updated to 0.9.3.5 in April, and it is also working.

**Comment by stsrki** [comment] 2021-06-28 14:44
@JaredMRomano Thank you for giving feedback. Since it is working I will close the ticket.

**Closed by stsrki** 2021-06-28 14:44 UTC
Labels: Status: Expecting Answer, Type: Bug 🐞
