### ISSUE TITLE
Tailwind Demo: CSS issue

### ISSUE THREAD

**Issue by MohamedAlaaTurki** [Megabit/Blazorise#4768] opened 2023-05-13 19:25 UTC
**Describe the bug**
The Navbar of the tailwind demo has a hover issue on "Home", "Documentation", "Github", and "Blazorise Demo" links where they disappear when hovered.
And the Forms page in tailwind demo has the wrong CSS for "Readonly", "Disabled", and "Static control", where the text is white on white white the rest of the form has a dark theme

**To Reproduce**
1. Go to 'https://tailwinddemo.blazorise.com/tests/forms'
2. Hover "Home", "Documentation", "Github", and "Blazorise Demo" from the top Navbar
3. Scroll down to "Readonly", "Disabled", and "Static control"
4. See how the CSS used has a light theme among the dark themed form

**Expected behavior**
While hovering "Home", "Documentation", "Github", or "Blazorise Demo", they will become white and disappear since the background is white.

**Screenshots**
![issue2](https://github.com/Megabit/Blazorise/assets/77687361/76649e25-4f2e-42e1-a017-b199a7ccab31)
![issue3](https://github.com/Megabit/Blazorise/assets/77687361/8a344f01-957d-4caa-afc5-8fbf9fc3c72e)

![issue](https://github.com/Megabit/Blazorise/assets/77687361/1450f2b6-7348-418e-8311-1dc26ac6286d)

**Comment by stsrki** [comment] 2023-05-13 19:30
I cannot reproduce it. On my system the hover color is blue

![image](https://github.com/Megabit/Blazorise/assets/900302/64fb1c91-18d7-42d2-92f1-d7d051157ef6)

---

What browser do you use?

**Comment by MohamedAlaaTurki** [comment] 2023-05-13 19:36
@stsrki 
I used both Opera Gx and Brave and got the bug on both

**Comment by stsrki** [comment] 2023-05-13 19:37
OK, I was able to reproduce it. It is indeed a bug. Should be fixed with the next release,.

**Comment by MohamedAlaaTurki** [comment] 2023-05-13 19:40
Thank you.

**Closed** 2023-05-31 18:42 UTC
Labels: Type: Bug 🐞
