### ISSUE TITLE
Castle Windsor does not work `ServerPrerendered`

### ISSUE THREAD

**Issue by astuy** [Megabit/Blazorise#2024] opened 2021-03-12 11:05 UTC
**Describe the bug**
I am using Castle Windsor as DI container. The Blazor Server template had `ServerPrerendered` as render mode for the App component set. After upgrading to 0.9.3 I got an ObjectDisposedException.
Setting render mode to `Server` works around the bug, but then my site takes hours to be presented to the user.

**To Reproduce**
Checkout my branch [`CastleWindsor`](https://github.com/astuy/Blazorise/tree/CastleWindsor) and start the Bootstrap.RC-project.

**Expected behavior**
No exception

**Stacktrace**
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Scope cache was already disposed. This is most likely a bug in the calling code.'.
   at Castle.MicroKernel.Lifestyle.Scoped.ScopeCache.set_Item(Object id, Burden value)
   at Castle.Windsor.Extensions.DependencyInjection.Scope.ExtensionContainerScope.GetCachedInstance(ComponentModel model, ScopedInstanceActivationCallback createInstance)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy)
   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)
   at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.DefaultKernel.ResolveComponent(IHandler handler, Type service, Arguments additionalArguments, IReleasePolicy policy, Boolean ignoreParentContext)
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, Arguments arguments, IReleasePolicy policy, Boolean ignoreParentContext)
   at Castle.MicroKernel.DefaultKernel.Resolve(Type service, Arguments arguments)
   at Castle.Windsor.Extensions.DependencyInjection.WindsorScopedServiceProvider.GetService(Type serviceType)
   at Blazorise.ComponentActivator.CreateInstance(Type componentType) in E:\Develop\Repos\Blazorise\Source\Blazorise\ComponentActivator.cs:line 36
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

**Comment by stsrki** [comment] 2021-03-12 11:13
I reproduce the error. Are you sure this is not the problem with Castle Windsor?

For example, we were using Blazorise with Autofac without any issue so far.

**Comment by astuy** [comment] 2021-03-12 11:15
Thanks for your quick confirmation.

I don't know Castle Windsor very well, just used it out of the box. But it worked with Blazorise 0.9.2, that's why I thought Blazorise has the bug.

**Comment by stsrki** [comment] 2021-03-12 11:18
In 0.9.3 I have introduced IComponentActivator which allows me to create components with DI. Previously that was only possible internally in Blazor and it was very unoptimized.

**Comment by astuy** [comment] 2021-03-12 11:21
Yeah, read about that. So before DI was not even used? Then it might be an issue with Castle Windsor. Don't know..

**Comment by stsrki** [comment] 2021-03-12 11:25
Yes, previously every (custom) component was created manually.

From what I can understand of Castle Windsor error it seems it might have problems with transient objects inside of the scoped instances. And components must be transient because they are created and destroyed all the time.

**Comment by astuy** [comment] 2021-03-12 11:34
Let's see, what they say.

**Comment by stsrki** [comment] 2021-03-16 16:10
Still nothing from CW team?

**Comment by astuy** [comment] 2021-03-17 16:11
> Still nothing from CW team?

No :-/

**Comment by astuy** [comment] 2021-07-15 14:43
Today I had some time to dig around in Castle Windsor and found, that during the final render the scope is already disposed, from where Blazorize components are tried to be created, though the Service Provider is still alive. Do you know where to find some documentation about DI scopes and ServerPrerendered?

**Comment by stsrki** [comment] 2021-10-29 20:21
Sorry, @astuy, your ticked got lost in the crowd. Were you able to fix it?

Registering as scoped might help. You can try removing IComponentActivator and reading it as scoped.

**Comment by astuy** [comment] 2021-11-01 06:51
Hi @stsrki, no worries. :) Indeed I worked around it that way and until now it works:

```C#
services.AddBlazorise()
    .AddBootstrapProviders();
services.Replace(ServiceDescriptor.Scoped<IComponentActivator, ComponentActivator>());
```

I don't know, whether the .NET and Blazor teams would solve it the same way, but for our use case there have not been any problems yet.
So in my opinion you could close the issue, if you want.

**Comment by stsrki** [comment] 2021-11-01 08:21
.NET team is not very fast to fix most of the issues, unfortunately.

OK Closing now :)

**Closed by stsrki** 2021-11-01 08:21 UTC
