### ISSUE TITLE
DatePicker Multiple Select Problem

### ISSUE THREAD

**Issue by raysefo** [Megabit/Blazorise#4692] opened 2023-03-23 08:43 UTC
Hi,

I can not select multiple dates from the date picker. 

```
<RadzenDataFilterProperty TItem="ReportViewModel" Property="OrderDateTime" Title="Order Date" FormatString="{0:d}" 
                                      FilterValue="@filteredDates"
                                      Type="typeof(IEnumerable<DateTime>)"
                                      FilterOperator="FilterOperator.Contains">
                <FilterTemplate>
                    <DatePicker Dates="selectedDates" TValue="DateTime" InputMode="DateInputMode.Date" SelectionMode="DateInputSelectionMode.Multiple"
                                DisplayFormat="dd/MM/Y" DatesChanged="@OnDatesChanged"/>
                </FilterTemplate>
            </RadzenDataFilterProperty>

@code {
    RadzenDataFilter<ReportViewModel> dataFilter;
    IEnumerable<ReportViewModel> filteredOrders;
    bool auto = true;
    
    IReadOnlyList<DateTime> selectedDates = new List<DateTime>().AsReadOnly();
    IEnumerable<DateTime> filteredDates;
    
    Task OnDatesChanged(IReadOnlyList<DateTime> values)
    {
        filteredDates = values.Cast<DateTime>();
        return Task.CompletedTask;
    }
}
```

Here is the sample demo;

https://user-images.githubusercontent.com/859957/227148897-5e8aaa6d-b2d2-43fe-b4c3-f9607cea03a8.mp4

**Comment by raysefo** [comment] 2023-03-24 13:59
Have you looked into this problem?

**Comment by David-Moreira** [comment] 2023-03-24 17:35
Hello @raysefo, 

Sorry not yet. But it's always best to reproduce the problem as a standalone, the example code you posted has some other party controls.
As you may expect we'll be making sure it works without the RadzenDataFilterProperty wrapper. Please let us know if you've already tested that.

**Comment by raysefo** [comment] 2023-03-24 19:32
Actually, it works with `@bind-Dates="selectedDates"`. But I need to use `DatesChanged="@OnDatesChanged"` in order to trigger manually.
`
```
<RadzenDataFilterProperty TItem="ReportViewModel" Property="OrderDateTime" Title="Order Date" FormatString="{0:d}"
                                      FilterValue="@filteredDates">
                <FilterTemplate>
                    <DatePicker @bind-Dates="selectedDates" TValue="DateTime" InputMode="DateInputMode.Date" SelectionMode="DateInputSelectionMode.Multiple" />
                </FilterTemplate>
            </RadzenDataFilterProperty>
```


https://user-images.githubusercontent.com/859957/227622206-711dba26-4782-4696-b8e1-53f780260078.mp4

**Comment by stsrki** [comment] 2023-03-24 20:00
It's because you don't assign to `selectedDates`.

**Needs to be**

```diff
Task OnDatesChanged(IReadOnlyList<DateTime> values)
{
+    selectedDates = values;
    filteredDates = values.Cast<DateTime>();
    return Task.CompletedTask;
}
```

**Comment by raysefo** [comment] 2023-03-25 05:08
Thank you.

**Closed** 2023-03-25 07:34 UTC
Labels: Type: Bug 🐞
