### ISSUE TITLE
[Bug]: Blazorise 1.5.1 Material UI modals stopped working

### ISSUE THREAD

**Issue by njannink** [Megabit/Blazorise#5437] opened 2024-04-01 13:57 UTC
### Blazorise Version

1.5.1

### What Blazorise provider are you running on?

Material

### Steps to reproduce

I updated to Blazorise 1.5.1 and my modals stopped working. I only see the shadow background, but the actual model isn't visible. I inspected the html and the actual modal and all content is being rendered. Only its not visible. Any idea what might have changed?

**Comment by stsrki** [comment] 2024-04-01 14:00
We made some changes to the modal animation with CSS. Try claring the cache and see it it helps. 

PS. our demo seem to be working https://materialdemo.blazorise.com/tests/modals

**Comment by njannink** [comment] 2024-04-01 14:03
Cleaning cache I already tried and didn't solve the issue. Also not something we can tell our customers

**Comment by stsrki** [comment] 2024-04-01 14:21
It usually helps just by adding the query version at the end of the link file, eg, 

`<link href="_content/Blazorise.Material/blazorise.material.css?v=1.5.1.0" rel="stylesheet" />`.

Do you have some other CSS in your project that might affect the modal?

**Comment by njannink** [comment] 2024-04-01 14:37
I found the issue. The modal stays on display: none. If I add this css it fixes my problem:

```
.modal.show {
    display: block;
}
```

With previous version making a modal visible would set this style on the div `display: block;--modal-animation-duration: 150ms`

**Comment by travelmarx** [comment] 2024-04-01 14:42
> It usually helps just by adding the query version at the end of the link file, eg,
> 
> `<link href="_content/Blazorise.Material/blazorise.material.css?v=1.5.1.0" rel="stylesheet" />`.
> 
> Do you have some other CSS in your project that might affect the modal?

Thanks! I was going crazy having updated from 1.4 to 1.5 with Bootstrap5 and modals stopped working. Yes, I could see it was only a display issue, but didn't think about using v=1.5.1 at the end of the stylesheet link in my case in app.razor.

**Comment by stsrki** [comment] 2024-04-01 14:52
Thanks, I will try to improve it for 1.5.2.

**Comment by njannink** [comment] 2024-04-03 13:53
@stsrki oops. The PR is closing the wrong defect. it should close #5439 and not this one

**Comment by stsrki** [comment] 2024-04-09 12:22
I'm unable to reproduce the problem on my side. Modal works as expected. Do you guys still have the same problem?

**Comment by stsrki** [comment] 2024-07-30 08:36
Closing as we were unable to reproduce.

**Closed by stsrki** 2024-07-30 08:36 UTC
Labels: Type: Bug 🐞
