### ISSUE TITLE
Sidebar not collapsing on appstart

### ISSUE THREAD

**Issue by Akdimi** [Megabit/Blazorise#2355] opened 2021-05-12 20:05 UTC
Hello, i'm trying to get the sidebar v9.2 to collapse when the app starts(its always open when app starts). I tried to set the bool value to false on initialsed and onafterender but its not working. But when i click on the bar icon it does collapse properly. Is this a bug in v9.2? Because in v9.3 it does work.  I m creating a hybrid app so i cant use v9.3 on the shared project netstandard2.1. Is there something i am missing?

**Comment by stsrki** [comment] 2021-05-12 20:25
Can you show some code of how you use Sidebar?

It is possible that there is a bug in the Sidebar component. Especially since v0.9.2 is now quite an old version. Also, the problem is that Sidebar component is obsolete and is being replaced with the Bar component that has much more features.

Your only option would be to move to v0.9.3 but since you're targeting netstandard2.1, it is not an option.

**Comment by Akdimi** [comment] 2021-05-12 21:00
<Bar 
     Visible="istoggled"
     Breakpoint="Breakpoint.Desktop"
     NavigationBreakpoint="Breakpoint.Tablet"
     ThemeContrast="ThemeContrast.Light"
     Mode="BarMode.VerticalPopout"
     CollapseMode="BarCollapseMode.Hide">
    
    <BarBrand>
        <BarItem>
            <BarLink To="">
                <BarIcon IconName="IconName.Store" />
                WebShop
            </BarLink>
        </BarItem>

    </BarBrand>
    <BarMenu>
        <BarStart>
            <BarItem>
                <BarLink To="" Match="Match.All">
                    <BarIcon IconName="IconName.Home" />
                    Home
                </BarLink>
            </BarItem>
            <AuthorizeView Roles="Admin">
                <Authorized>
                    <BarItem>
                        <BarLink To="products">
                            <BarIcon IconName="IconName.ShoppingCart" />
                            Products
                        </BarLink>
                    </BarItem>
                    <BarItem>
                        <BarLink To="stock">
                            <BarIcon IconName="IconName.Edit" />
                            Stock
                        </BarLink>
                    </BarItem>
                    <BarItem>
                        <BarLink To="orders">
                            <BarIcon IconName="IconName.CartPlus" />
                            Orders
                        </BarLink>
                    </BarItem>
                </Authorized>
            </AuthorizeView>
            <BarItem>
                <BarDropdown>
                    @if (Isrender)
                    { 
                        <BarDropdownToggle>
                            <BarIcon IconName="IconName.Edit" />
                            Dropdown
                        </BarDropdownToggle>
                    }

                    <BarDropdownMenu>
                        <BarDropdownItem>Action</BarDropdownItem>
                        <BarDropdownItem>Another action</BarDropdownItem>
                    </BarDropdownMenu>
                </BarDropdown>
            </BarItem>
        </BarStart>
    </BarMenu>
</Bar>



@code {
    @code{
        bool Isrender = false;

        bool istoggled = false;
        protected override Task OnAfterRenderAsync(bool firstRender)
        {
            Isrender = firstRender;
            Istoggled =false;
            return base.OnAfterRenderAsync(firstRender);

        }
        public void ToggleNavMenu()
        {
            istoggled = !istoggled;
            StateHasChanged();
        }
        RenderFragment customIcon =@<img src="~/images/almeria.jpg" style="width:32px; height: 32px" />;
    }

}

**Comment by Akdimi** [comment] 2021-05-12 21:01
It should work because i have the same code working in .net5 and v9.3

**Comment by stsrki** [comment] 2021-05-12 21:08
This was a bug in v0.9.2 that was only fixed in a later version. See here https://github.com/stsrki/Blazorise/issues/1617

**Comment by Akdimi** [comment] 2021-05-12 21:18
> This was a bug in v0.9.2 that was only fixed in a later version. See here #1617

Any chance it will get fixed?

**Comment by stsrki** [comment] 2021-05-13 05:55
Unfortunately, it is not possible. Usually, I support only the latest version while I work on the new `dev `branch. Having support for the older version would just take too much time, which is already limited. And on top of it, I really don't have the `sup092` branch anymore.

**Closed** 2021-05-31 15:05 UTC

**Comment by Akdimi** [comment] 2021-05-31 15:06
Thanks for the clarification👍
