### ISSUE TITLE
Mode="BarMode.VerticalInline" throws JS Interop Unhandled Exception on Blazor Server app

### ISSUE THREAD

**Issue by JGSilverman** [Megabit/Blazorise#2786] opened 2021-08-06 18:29 UTC
In my MainLayout.Razor i have a cut and paste from your docs:

```
<Layout>
    <LayoutHeader Fixed="true">
        <nav class="navbar">
            <span>temp navbar</span>
        </nav>
    </LayoutHeader>
    <Layout Sider="true">
        <LayoutSider>
            <LayoutSiderContent>
                <Bar Mode="BarMode.VerticalInline"
                     CollapseMode="BarCollapseMode.Small"
                     Breakpoint="Breakpoint.Desktop"
                     NavigationBreakpoint="Breakpoint.Tablet"
                     ThemeContrast="ThemeContrast.Dark">
                    <BarBrand>
                        <BarItem>
                            <BarLink To="">
                                <BarIcon IconName="IconName.Dashboard" />
                                Blazorise Demo
                            </BarLink>
                        </BarItem>
                    </BarBrand>
                    <BarMenu>
                        <BarStart>
                            <BarItem>
                                <BarLink To="#home">
                                    <BarIcon IconName="IconName.Dashboard" />
                                    Home
                                </BarLink>
                            </BarItem>
                            <BarItem>
                                <BarLink To="#docs">Documentation</BarLink>
                            </BarItem>
                            <BarItem>
                                <BarDropdown>
                                    <BarDropdownToggle>
                                        <BarIcon IconName="IconName.Edit" />
                                        Dropdown
                                    </BarDropdownToggle>
                                    <BarDropdownMenu>
                                        <BarDropdownItem>Action</BarDropdownItem>
                                        <BarDropdownItem>Another action</BarDropdownItem>
                                    </BarDropdownMenu>
                                </BarDropdown>
                            </BarItem>
                        </BarStart>
                    </BarMenu>
                </Bar>
            </LayoutSiderContent>
        </LayoutSider>
        <Layout>
            <LayoutContent>
                @Body
            </LayoutContent>
        </Layout>
    </Layout>
</Layout>

```
In _host.cshtml _head,_ I have the following:

```
<link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />

    <link rel="prefetch" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/default.min.css" as="style">
    <link rel="prefetch" href="css/scroll-view.css" as="style">
    <link href="_content/Blazored.Typeahead/blazored-typeahead.css" rel="stylesheet" />
    <link href="css/site.css" rel="stylesheet" />
    <link rel="stylesheet" href="css/dx-demo.css">
    <link rel="stylesheet" href="css/dx-blazor.css">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">

    <link href="_content/Blazorise/blazorise.css" rel="stylesheet" />
    <link href="_content/Blazorise.Bootstrap/blazorise.bootstrap.css" rel="stylesheet" />
```
In _host.cshtml _body,_ I have the following:
```

<body>
    <app>
        @*//Caching*@
        <component type="typeof(App)" render-mode="ServerPrerendered" />
    </app>

    <div id="blazor-error-ui">
        <environment include="Staging,Production">
            An error has occurred. This application may no longer respond until reloaded.
        </environment>
        <environment include="Development">
            An unhandled exception has occurred. See browser dev tools for details.
        </environment>
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

    <script src="_content/Blazorise/blazorise.js"></script>
    <script src="_content/Blazorise.Bootstrap/blazorise.bootstrap.js"></script>
    <script src="_framework/blazor.server.js"></script>
    <script src="_content/Blazored.Typeahead/blazored-typeahead.js"></script>
</body>
```

_Imports.razor has @using Blazorize per docs.

Startup.cs has the following service registration plus required using statements.

```
services
              .AddBlazorise(options =>
              {
                  options.ChangeTextOnKeyPress = true; // optional
              })
              .AddBootstrapProviders()
              .AddFontAwesomeIcons();
```

Index.razor is all generic html, no code yet.

Running the Blazor server app throws:

```
An unhandled exception occurred while processing the request.
InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendererd. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.
Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(long asyncHandle, string identifier, string argsJson)

Stack Query Cookies Headers Routing
InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendererd. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.
```

If I remove Mode="BarMode.VerticalInline" from the Bar Element, the app loads.

**Comment by stsrki** [comment] 2021-08-07 10:19
Are you on the latest 0.9.4.x version?

**Comment by stsrki** [comment] 2021-08-07 10:21
I cannot reproduce the error.

**Comment by JGSilverman** [comment] 2021-08-07 21:19
We're not. We're on 0.9.1 because we're on .NET Core 3.1. 0.9.4 font awesome doesn't work with .NET Core 3.1

**Comment by stsrki** [comment] 2021-08-07 21:30
In the older Blazorise version JSInterop was wrongly called in OnInitialize. That's why you're seeing the error. That was fixed in one of the latest versions. Unfortunately, there is no way to fix 0.9.1 at this point as I don't keep or support the old versions. Your only and best option is to upgrade if possible.

Can you explain what you meant by saying _0.9.4 font awesome doesn't work with .NET Core 3.1_? I'm not sure why font-awesome would be tied to a specific .Net version?

**Comment by JGSilverman** [comment] 2021-08-07 21:45
When downloading the latest version of Blazorise.FontAwesome via Nuget on .NET Core 3.1 app, it threw an error saying 0.9.4 wasn't compatible with 3.1. I didn't have that same error with Blazorize.Bootstrap, just the font awesome package. Which is why I downgraded to 9.1

**Comment by stsrki** [comment] 2021-08-08 10:49
It's not the problem with the FontAwesome package. Since v0.9.3, Blazorise support only .Net 5 and up. .NET Core 3.1 was dropped because it didn't support `IComponentActivator` which was needed to implement some core iptimizations at the moment.

**Closed** 2021-08-09 07:24 UTC
