### ISSUE TITLE
RichTextEdit - GetHtmlAsync() hangs unless triggered with UI interaction

### ISSUE THREAD

**Issue by ssinghm32** [Megabit/Blazorise#4350] opened 2022-12-01 04:34 UTC
I have 3 RichTextEditors on a single Blazor page.

In an Async Task OnClickSave(), I am trying to get the content a user entered into these text editors by using .GetHtmlAsync() method call.

e.g.
var notes = await rteNotes.GetHtmlAsync();
var nextSteps = await rteNextSteps.GetHtmlAsync();
var agenda = await rteAgenda.GetHtmlAsync();

The system is able to correctly process for the notes but then returns control back to the UI and does nothing.  Unless I type something in the NextStep or Agenda text editor which somehow triggers processing for the other 2 calls.

NOTE: I am using a Blazor view in a .NET Maui App.  Not sure if this makes a difference.

**Comment by stsrki** [comment] 2022-12-01 06:49
The issue is already fixed with #4340, and it will be released with 1.1.5. We noticed the same thing with Markdown after the last update. 

Closing now.

**Closed by stsrki** 2022-12-01 06:49 UTC
Labels: Type: Bug 🐞
