### ISSUE TITLE
 blazorise bootstrap5 maui SelectList issue

### ISSUE THREAD

**Issue by jababda** [Megabit/Blazorise#3444] opened 2022-02-14 11:49 UTC
**Describe the bug**
SelectList is not displaying when clicked in an MAUI app. Flickers on click.

**To Reproduce**
1. Create a Maui app, add Blazorise boot strap 5. https://blazorise.com/docs/usage/bootstrap5
2. Add a SelectList component
3. Click select list

**Expected behavior**
Components should behave the same in all applications that can consume blazor.

**Sample Repo**
https://github.com/jababda/blazorise-bootstrap5-maui-issue
Requires VS2022 preview to run a MAUI project.

**Additional Info**
There might be some other issues as well with bootstrap5 in maui. In another project it errors on disposing some of the components. This might be something to do with the services Messages/Notifications but I have not reproduced those in the demo project.
It might be worth adding a test winform + maui app with the blazor web viewer.
`
Error: JS object instance with ID 1 does not exist (has it been disposed?).
    at S (https://0.0.0.0/_framework/blazor.webview.js:1:2459)
    at https://0.0.0.0/_framework/blazor.webview.js:1:3325
    at new Promise (<anonymous>)
    at beginInvokeJSFromDotNet (https://0.0.0.0/_framework/blazor.webview.js:1:3306)
    at https://0.0.0.0/_framework/blazor.webview.js:1:40526
    at EventTarget.<anonymous> (<anonymous>:7:80)
    at <anonymous>:1:355
`

**Comment by jababda** [comment] 2022-02-24 07:18
I've also noticed that this occurs with the `Autocomplete` component

**Comment by David-Moreira** [comment] 2022-03-26 17:55
Hello @jababda 

MAUI is still young and is not out officially right? 
With that in mind, we can still try to help you with making everything work fine as it's release should be nearing.

We are still not very proficient with MAUI, I have installed MAUI, and I started by trying out an example using native blazor components, and the flicker problem happens which makes me believe this might not be an issue with Blazorise?

This is what I tried, and I removed any blazorise resources you had in your index.html.
With this in mind, can you please troubleshoot making sure if the problem is actually Blazorise related?

```
<EditForm Model="Model">
<InputSelect TValue="string" @bind-Value="Model.TestString">
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
</InputSelect>
</EditForm>

@code{
    public Test Model { get; set; } = new Test();
    public class Test
    {
        public string TestString { get; set; }
    }
}
```

As for the problems with  `Messages/Notifications` we'll be taking a look. Actually we should be implementing a Blazorise MAUI demo in the near future, to help with making sure Blazorise works well with MAUI.

**Comment by jababda** [comment] 2022-03-27 14:25
I raised this after migrating from radzen which worked as it did in a normal blazor app.  At the time i didn't realize just how early access MAUI was.

After updating everything (Blazorise + vs) to the latest most issues have resolved.
Notification styling in bootstrap 5 are having some issues but thats the only thing I've noticed after the latest releases. 

With that in mind I'm happy to for this to be closed.

**Comment by David-Moreira** [comment] 2022-03-27 16:39
Hello @jababda,
Glad to know most stuff is working fine by now.

That's good to know, Is the notification styling you found a general issue with blazorise bs5 provider meaning it will happen on regular blazor? Or  does it happen just with MAUI?

**Comment by stsrki** [comment] 2022-03-29 09:31
So if I'm understating it, this is now working and we can close the ticker, right? @jababda

**Comment by jababda** [comment] 2022-03-31 09:32
> Hello @jababda, Glad to know most stuff is working fine by now.
> 
> That's good to know, Is the notification styling you found a general issue with blazorise bs5 provider meaning it will happen on regular blazor? Or does it happen just with MAUI?

I'm not sure. I haven't had the time to create a test repo with it. The Notifications look like in maui using bootstrap 5.
![image](https://user-images.githubusercontent.com/6836083/161024154-1d2d0aba-4516-4cc5-befd-7945176fa5bd.png)

> So if I'm understating it, this is now working and we can close the ticker, right? @jababda

Yes unless you'd like to keep this open to track the notification problem.

**Comment by stsrki** [comment] 2022-03-31 09:37
OK, thanks. I'm closing now since @David-Moreira already has another ticket for MAUI setup.

**Closed by stsrki** 2022-03-31 09:37 UTC
Labels: Type: Bug 🐞
