### ISSUE TITLE
can't call RichTextEditor.GetHtmlAsync

### ISSUE THREAD

**Issue by zhangzq71** [Megabit/Blazorise#4416] opened 2022-12-27 15:17 UTC
**Describe the bug**
A call the RichTextEditor.GetHtmlAsync, GetDeltaAsync does not return

**To Reproduce**
1. Open the RichTextEditPage 
2. type in the RichText control
3. nothing happend

**Expected behavior**
every OnContentChanged event will cause a GetHtmlAsync call, and display the html, but nothing happen

**Comment by stsrki** [comment] 2022-12-27 15:18
Can you tell us what Blazorise version you use?

**Comment by zhangzq71** [comment] 2022-12-27 15:30
It is the version pull from server, it is 019c580. The demo is the same

**Comment by stsrki** [comment] 2022-12-27 18:31
It's possible we didn't upload the latest version of the demo application. But the fix should already be released with v1.1.5. I'm also testing locally, and it seems to be working fine.

**Comment by zhangzq71** [comment] 2022-12-27 23:43
> It's possible we didn't upload the latest version of the demo application. But the fix should already be released with v1.1.5. I'm also testing locally, and it seems to be working fine.

Thank you for your reply, it did work.

**Comment by stsrki** [comment] 2022-12-28 06:22
> Thank you for your reply, it did work.

Can we close the ticket now?

**Comment by Mr-Pearce** [comment] 2023-01-10 11:57
I Have the same problem
Dotnet 6.0.12
Blazorise 1.1.5
Running on linux Docker if it matters.

Test Site to Reproduce:
```
@page "/test"
<h3>Test</h3>

<RichTextEdit @ref="richTextEditRef" Style="height:412px"
              Theme="RichTextEditTheme.Snow"
              ContentChanged="@OnContentChanged"
              PlaceHolder="Release Text hier eingeben"
              SubmitOnEnter="false"
              ToolbarPosition="Placement.Top">

    <Editor></Editor>
    <Toolbar>
        <RichTextEditToolbarGroup>
            <RichTextEditToolbarButton Action="RichTextEditAction.Bold" />
            <RichTextEditToolbarButton Action="RichTextEditAction.Italic" />
            <RichTextEditToolbarButton Action="RichTextEditAction.Underline" />
            <RichTextEditToolbarButton Action="RichTextEditAction.Blockquote" />
            <RichTextEditToolbarButton Action="RichTextEditAction.CodeBlock" />
            <RichTextEditToolbarSelect Action="RichTextEditAction.Size">
                <RichTextEditToolbarSelectItem Value="small" />
                <RichTextEditToolbarSelectItem Selected />
                <RichTextEditToolbarSelectItem Value="large" />
                <RichTextEditToolbarSelectItem Value="huge">Very Big</RichTextEditToolbarSelectItem>
            </RichTextEditToolbarSelect>
            <RichTextEditToolbarButton Action="RichTextEditAction.List" Value="ordered" />
            <RichTextEditToolbarButton Action="RichTextEditAction.List" Value="bullet" />
        </RichTextEditToolbarGroup>
        <!-- Custom toolbar content -->
        <RichTextEditToolbarGroup Float="Float.End">
            <Button Clicked="@(()=> commentsVisible = !commentsVisible)"><Icon Name="IconName.Comments" /></Button>
        </RichTextEditToolbarGroup>
    </Toolbar>
</RichTextEdit>

@code {
    RichTextEdit? richTextEditRef;
    bool commentsVisible;
    string releaseText;
    public async Task OnContentChanged()
    {
        releaseText = await richTextEditRef.GetHtmlAsync(); //<-- Stops here
        UpdateButtonText(); // never gets here
    }

    public void UpdateButtonText()
    {

    }
}

```

**Comment by Mr-Pearce** [comment] 2023-01-10 11:58
> > Thank you for your reply, it did work.
> 
> Can we close the ticket now?

@stsrki 
I Have the same problem
Dotnet 6.0.12
Blazorise 1.1.5
Running on linux Docker if it matters.

Test Site to Reproduce:
```
@page "/test"
<h3>Test</h3>

<RichTextEdit @ref="richTextEditRef" Style="height:412px"
              Theme="RichTextEditTheme.Snow"
              ContentChanged="@OnContentChanged"
              PlaceHolder="Release Text hier eingeben"
              SubmitOnEnter="false"
              ToolbarPosition="Placement.Top">

    <Editor></Editor>
    <Toolbar>
        <RichTextEditToolbarGroup>
            <RichTextEditToolbarButton Action="RichTextEditAction.Bold" />
            <RichTextEditToolbarButton Action="RichTextEditAction.Italic" />
            <RichTextEditToolbarButton Action="RichTextEditAction.Underline" />
            <RichTextEditToolbarButton Action="RichTextEditAction.Blockquote" />
            <RichTextEditToolbarButton Action="RichTextEditAction.CodeBlock" />
            <RichTextEditToolbarSelect Action="RichTextEditAction.Size">
                <RichTextEditToolbarSelectItem Value="small" />
                <RichTextEditToolbarSelectItem Selected />
                <RichTextEditToolbarSelectItem Value="large" />
                <RichTextEditToolbarSelectItem Value="huge">Very Big</RichTextEditToolbarSelectItem>
            </RichTextEditToolbarSelect>
            <RichTextEditToolbarButton Action="RichTextEditAction.List" Value="ordered" />
            <RichTextEditToolbarButton Action="RichTextEditAction.List" Value="bullet" />
        </RichTextEditToolbarGroup>
        <!-- Custom toolbar content -->
        <RichTextEditToolbarGroup Float="Float.End">
            <Button Clicked="@(()=> commentsVisible = !commentsVisible)"><Icon Name="IconName.Comments" /></Button>
        </RichTextEditToolbarGroup>
    </Toolbar>
</RichTextEdit>

@code {
    RichTextEdit? richTextEditRef;
    bool commentsVisible;
    string releaseText;
    public async Task OnContentChanged()
    {
        releaseText = await richTextEditRef.GetHtmlAsync(); //<-- Stops here
        UpdateButtonText(); // never gets here
    }

    public void UpdateButtonText()
    {

    }
}

```

**Comment by stsrki** [comment] 2023-01-10 13:16
@Mr-Pearce, I'm testing your code and it works as expected. It doesn't stop on GetHtmlAsync.

**Comment by Mr-Pearce** [comment] 2023-01-10 13:43
[RtfTest.zip](https://github.com/Megabit/Blazorise/files/10383211/RtfTest.zip)
I Made a small Project with the nugets i use.
Can reproduce it by just Pressing F5 and writing into the RTF

**Comment by aastovas** [comment] 2023-01-10 15:25
Hello, I have the same issue, for the time being, I reverted to version 1.1.3 and it worked again

**Closed** 2023-01-10 23:41 UTC
Labels: Type: Bug 🐞, Status: Repro Missing

**Comment by stsrki** [comment] 2023-01-11 06:25
@zhangzq71 any reason why you closed it? It started working for you?

**Comment by zhangzq71** [comment] 2023-01-11 08:47
> 

@stsrki it works when using the code pull from github now.

**Comment by stsrki** [comment] 2023-01-11 09:18
OK. If the issue still happens after we release 1.1.6, then please reopen it.

**Comment by zhangzq71** [comment] 2023-01-11 15:40
but this issue had been fixed in 1.1.5

**Comment by Mr-Pearce** [comment] 2023-01-13 10:32
> but this issue had been fixed in 1.1.5

If you scroll a bit up you will see that i still have the problem with 1.1.5

**Comment by Mr-Pearce** [comment] 2023-01-18 08:34
@stsrki Just wanted to tell you that now with 1.1.6 it works like intended 👍

**Comment by stsrki** [comment] 2023-01-18 09:34
Thank you for letting us know. 

Closing the ticket now.
