### ISSUE TITLE
DateEdit for date and time not working in Firefox

### ISSUE THREAD

**Issue by sourcetonuts** [Megabit/Blazorise#2445] opened 2021-06-03 14:27 UTC
**Describe the bug**
DateEdit not working in Firefox (looks like blank text) in input mode InputMode="DateInputMode.DateTime" 
Executing demo from github or latest nugets.

                <Field Horizontal="true">
                    <FieldLabel ColumnSize="ColumnSize.IsFull.OnTablet.Is2.OnDesktop">Date and Time</FieldLabel>
                    <FieldBody ColumnSize="ColumnSize.IsFull.OnTablet.Is10.OnDesktop">
                        <DateEdit TValue="DateTime?" InputMode="DateInputMode.DateTime" />
                    </FieldBody>
                </Field>

**To Reproduce**
Run demo code and w/ razor above from github in FireFox.

**Expected behavior**
Ability to select/display DateTime as in Chrome ++

Blazorise Demo as-is from repo.

**Screenshots**
![image](https://user-images.githubusercontent.com/189883/120661382-362bbe00-c456-11eb-9a9d-974902f39a89.png)

**Additional context**
none.

**Comment by stsrki** [comment] 2021-06-03 17:26
Yeah, it seems on Firefox it has limited support https://caniuse.com/input-datetime

Not much I can do there. In v0.9.4 we will introduce a new DatePicker component that is not limited by browsers. If you want to try a preview it is already available.

**Comment by stsrki** [comment] 2021-07-06 14:48
Closing since the problem is in browser support and we will have a new component in the new release.

**Closed by stsrki** 2021-07-06 14:48 UTC

**Comment by swaipa** [comment] 2021-11-09 08:21
Hi
We are running 0.9.4.7 and the DateEdit doesn't show the time section of the dropdown when using FireFox.
Is it still the old component?

**Comment by stsrki** [comment] 2021-11-09 10:50
@swaipa DateEdit is built around the native input component and as such is controlled by the browser. You can see the same behavior on the Mozilla docs: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local#browser_compatibility

**Comment by swaipa** [comment] 2021-11-11 09:09
Hey
Thanks for the info - apparently your DateEdit in InputMode="DateInputMode.DateTime" doesn't behave as <input type="datetime-local">

This is me using your DateEdit:

![Blazorise DateEdit FireFox](https://user-images.githubusercontent.com/9133169/141269726-9623c57a-7adb-4f3a-b989-4c178bcfa0d8.gif)
