### ISSUE TITLE
[Bug]: "System.InvalidOperationException: The render handle is not yet assigned." when using "ModalRenderMode.LazyReload"

### ISSUE THREAD

**Issue by ageiter** [Megabit/Blazorise#5694] opened 2024-08-14 15:06 UTC
### Blazorise Version

1.5.2

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction or a simple code snippet

```
<Modal @ref="IncidentModalDialog" Closing="@IncidentModalDialog.CancelClosingModalWhenFocusLost" RenderMode="ModalRenderMode.LazyReload">
    <ModalContent Centered>
        <ModalBody>
            <Validations @ref="@IncidentValidations"
                         Mode="ValidationMode.Manual"
                         Model="@IncidentModel"
                         ValidateOnLoad="false"
                         HandlerType="typeof(FluentValidationHandler)">
                    <Validation MessageLocalizer="@LH.Localize">
                        <Field>
                            <FieldLabel RequiredIndicator="@IncidentModel.TerminationModel.IsTerminationAlreadyOccurred">@L["Page:Termination:IncidentModal:StartDate:Label"]:</FieldLabel>
                            <DateEdit TValue="DateOnly?" InputMode="DateInputMode.Date" @bind-Date="@IncidentModel.StartDate">
                                <Feedback>
                                    <ValidationError/>
                                </Feedback>
                            </DateEdit>
                        </Field>
                    </Validation>
            </Validations>
        </ModalBody>
    </ModalContent>
</Modal>
``` 

```c#
    private async Task OpenNewIncidentModalDialogAsync()
    {
        IncidentModel = new IncidentViewModel
        {
            IsNew = true,
            Id = Guid.NewGuid(),
            TerminationId = TerminationId,
            TerminationModel = TerminationModel!
        };

        await IncidentValidations.ClearAll();
        await IncidentModalDialog.Show();
    }
``` 

### Steps to reproduce

As soon as I use the RenderMode `ModalRenderMode.LazyReload` or `ModalRenderMode.LazyLoad` in Modal control, I get the error message below when call `Show()`. It only works with RenderMode `ModalRenderMode.Default`.

### What is expected?

Modal is opened correctly and redrawn.

### What is actually happening?

**Exception:** 

[2024-08-14T14:47:45.767Z] Error: System.InvalidOperationException: The render handle is not yet assigned.
   at Microsoft.AspNetCore.Components.RenderHandle.ThrowNotInitialized()
   at Microsoft.AspNetCore.Components.ComponentBase.InvokeAsync(Func`1 workItem)
   at Blazorise.Validations.RaiseStatusChanged(ValidationStatus status, IReadOnlyCollection`1 messages, IValidation validation)
   at Blazorise.Validations.ClearAll()
   at Palma.Blazor.Pages.Termination.OpenEditIncidentModalDialogAsync(IncidentViewModel model) in D:\Projects\Palma\Source\Palma\src\Palma.Blazor\Pages\Termination.razor.cs:line 147
   at Palma.Blazor.Pages.Termination.<>c__DisplayClass69_0.<<BuildRenderTree>b__114>d.MoveNext() in D:\Projects\Palma\Source\Palma\src\Palma.Blazor\Pages\Termination.razor:line 277
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Blazorise.Button.ClickHandler(MouseEventArgs eventArgs)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

### What browsers do you see the problem on?

Microsoft Edge

**Comment by David-Moreira** [comment] 2024-08-14 15:16
Hello @ageiter 
The `System.InvalidOperationException: The render handle is not yet assigned. ` is tipically thrown when the "blazor engine is not running" let's say.

So it's probable that:
- You're trying to Show() when the component is pre-rendering
- You're using  **.NET 8 SSR** which is not supported by Blazorise. Blazorise only fully supports **Interactive Modes**.

If you're unable to troubleshoot these hypothesis, please provide a full reproducible of the issue as it's most likely related to how you have things setup and not the component itself.

Here's an example of the modals working correctly in Blazor WebAssembly : 
https://bootstrapdemo.blazorise.com/tests/modals

**Comment by ageiter** [comment] 2024-08-14 15:28
Hi @David-Moreira, thank you for your feedback. 

Then I guess this will not work with Blazor Server, which I am using... 

My problem is that the second time I open the modal, it is not re-rendered and therefore the RequiredIndicator is not displayed if the property has changed to true in the meantime. Would you have a tip for me?

**Comment by David-Moreira** [comment] 2024-08-14 15:34
> Hi @David-Moreira, thank you for your feedback.
> 
> Then I guess this will not work with Blazor Server, which I am using...
> 
> My problem is that the second time I open the modal, it is not re-rendered and therefore the RequiredIndicator is not displayed if the property has changed to true in the meantime. Would you have a tip for me?

Hello,

**Blazor server** is what what we call nowadays in the new **.NET8 Web App** as **InteractiveServer** and it is **supported**.

> My problem is that the second time I open the modal, it is not re-rendered and therefore the RequiredIndicator is not displayed if the property has changed to true in the meantime. Would you have a tip for me?

Sorry I don't follow, wasn't the problem that an exception was thrown? But you're telling us it renders but things are not updated? Can you please clarify? 

Again, if you believe you're not doing anything wrong, we recommend that you provide us with a Repro so we can take a look at your individual case.

**Comment by ageiter** [comment] 2024-08-14 15:41
Sorry if I communicated too imprecisely. 

If I use the default RenderMode, the rendering works, but I have the problem that the property "RequiredIndicator" was not updated on the second display. That's why I wanted to use the other RenderMode, where it should be re-rendered each time it is displayed. And with this one the exception occurred.

**Comment by David-Moreira** [comment] 2024-08-14 15:50
The exception is not expected in **Blazor.Server**, could I kindly request that you provide the repro for us? That'd be much appreciated.

By using the `ModalRenderMode.LazyReload` option the `Modal` should reload each time and Parameters like the label `Required` which are only considered when the component first initializes, will be reevaluated.

Another workaround I can think off, and it might seem a bit dumb, but it should work : 
`<FieldLabel @key=@IncidentModel.TerminationModel.IsTerminationAlreadyOccurred RequiredIndicator="@IncidentModel.TerminationModel.IsTerminationAlreadyOccurred">`

By assigning the key attribute, once the `IsTerminationAlreadyOccurred` changes and the label will be completely re-rendering therefore triggeting the initialization process.
This attribute is typically used when you generate html based on collections, but it should work for the purpose of reinitializing a component once this value changes.
Please be advised that the key attribute should typically contain unique values, but it should be fine in this case.

**Comment by David-Moreira** [comment] 2024-08-14 15:59
@ageiter I just noticed something in your example that also might be causing the render handle error.

By using the `RenderMode="ModalRenderMode.LazyReload"` or **LazyLoad** modes the structure inside the modal will not be rendered right away. This means that `IncidentValidations` will not be in the expected state to call `ClearAll()` as it will have to render.

**Try this calling Show() first and then ClearAll():**

```
        await IncidentModalDialog.Show();
        await IncidentValidations.ClearAll();
```

**Comment by ageiter** [comment] 2024-08-15 08:46
Thanks @David-Moreira for your tips and help. This enabled me to find a working solution.

> Another workaround I can think off, and it might seem a bit dumb, but it should work :
<FieldLabel @key=@IncidentModel.TerminationModel.IsTerminationAlreadyOccurred RequiredIndicator="@IncidentModel.TerminationModel.IsTerminationAlreadyOccurred">

Your workaround works perfectly. I could use this if I keep the `RenderMode.Default`.

>  This means that IncidentValidations will not be in the expected state to call ClearAll() as it will have to render.

Changing the order did not work. 
But when I use `RenderMode.LazyReload`, the validator is recreated anyway. So I don't need to execute the `ClearAll()` at all. And then it works the way I expect :-)

You can close the issue. Thank you very much for your help!

**Comment by David-Moreira** [comment] 2024-08-15 08:57
> Changing the order did not work.

You'd probably need to add something like `Task.Yield()` in order to give time for the engine to assign the ref properly. 
The thing is that the modal needs to show, the validations component needs to render, and the ref needs to be assigned before being able to `await IncidentValidations.ClearAll();` but you're right, since it re-renders, there's no point in calling it anyway or loosing time with it, nice catch.

Closing issue as there wasn't any problem. Glad you got it working as expected.

**Closed by David-Moreira** 2024-08-15 08:57 UTC
Labels: Type: Bug 🐞, Status: Repro Missing

**Comment by ageiter** [comment] 2024-08-15 09:32
Oh, that's a great tip and it worked perfectly! Even though I don't need it here now, I learned something and was able to use it directly in another place where I had to wait for the rendering to finish.
