### ISSUE TITLE
Application crashing after update from 1.0.7 tot 1.1.3.1

### ISSUE THREAD

**Issue by TacoWannee** [Megabit/Blazorise#4288] opened 2022-11-11 09:39 UTC
When I update my project to .Net7 and update all packages to the latest version, my application is not working at all:
![image](https://user-images.githubusercontent.com/108428600/201305631-820ea29f-1ad1-4039-90fe-0f4bae5d618a.png)
Switching to version 1.1.2 gives the same problem.
Returning back to the 1.0.7 makes it work again.

Am I missing some migration stuff?

**Comment by stsrki** [comment] 2022-11-11 11:27
It seems we didn't correctly define net7 bindings. Thanks for letting us know. We will try to fix it for the next patch.

**Comment by David-Moreira** [comment] 2022-11-13 11:41
I wasn't able to actually reproduce this.
@TacoWannee can I ask you that you retest this? We had a temporary time frame where we had a missing package on nuget.

If you're still getting the same error, can you provide a repro? Thanks!

**Comment by TacoWannee** [comment] 2022-11-14 12:30
Because of some package complications with .Net7 in my application, I fall back to .Net6 again. I get the same problems with Blazorise 1.1.3.1. using .Net6 now, so I stay with Blazorise 1.0.x for now.

**Comment by David-Moreira** [comment] 2022-11-14 21:58
Gotcha. That's a shame. We'll try to do some more testing, see if we find what's wrong.

But it would really be helpful if you could provide a repo with the actual problem.

**Comment by tacoWanneeJama** [comment] 2022-11-21 07:46
My client projectfile:

<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<RootNamespace>ws4.Client</RootNamespace>
		<AssemblyName>ws4.Client</AssemblyName>
		<AssemblyVersion>0.0.8.0</AssemblyVersion>
		<FileVersion>0.0.8.0</FileVersion>
		<Version>0.0.7</Version>
		<VersionPrefix>0.0.8.0</VersionPrefix>
		<ApplicationIcon></ApplicationIcon>
		<TypeScriptModuleKind>umd</TypeScriptModuleKind>
		<Configurations>Debug;Release;ReleaseTest</Configurations>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <DefineConstants>LIVESHARP_DISABLE</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='ReleaseTest|AnyCPU'">
	  <DefineConstants>LIVESHARP_DISABLE</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <DefineConstants>DEBUG</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
	  <Content Remove="bundleconfig.json" />
	  <Content Remove="compilerconfig.json" />
	  <Content Remove="wwwroot\test.ts" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="bundleconfig.json" />
	  <None Include="compilerconfig.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="12.0.0" />
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
		<PackageReference Include="Blazor.ContextMenu" Version="1.14.0" />
		<PackageReference Include="Blazor.Extensions.Canvas" Version="1.1.1" />
		<PackageReference Include="Blazored.LocalStorage" Version="4.3.0" />
		<PackageReference Include="Blazored.SessionStorage" Version="2.2.0" />
		<PackageReference Include="Blazorise" Version="1.0.7" />
		<PackageReference Include="Blazorise.Bootstrap5" Version="1.0.7" />
		<PackageReference Include="Blazorise.Charts" Version="1.0.7" />
		<PackageReference Include="Blazorise.Components" Version="1.0.7" />
		<PackageReference Include="Blazorise.DataGrid" Version="1.0.7" />
		<PackageReference Include="Blazorise.Icons.FontAwesome" Version="1.0.7" />
		<PackageReference Include="Blazorise.Sidebar" Version="1.0.7" />
		<PackageReference Include="Blazorise.Snackbar" Version="1.0.7" />
		<PackageReference Include="BlazorPro.BlazorSize" Version="6.1.2" />
		<PackageReference Include="BootstrapBlazor.SignaturePad" Version="6.2.1" />
		<PackageReference Include="Darnton.Blazor.Leaflet" Version="0.1.3">
			<Aliases></Aliases>
		</PackageReference>
		<PackageReference Include="geojson.TypeScript.DefinitelyTyped" Version="0.3.8" />
		<PackageReference Include="leaflet-markercluster.TypeScript.DefinitelyTyped" Version="0.0.5" />
		<PackageReference Include="leaflet.TypeScript.DefinitelyTyped" Version="0.7.4" />
		<PackageReference Include="Microsoft.AspNetCore.Authorization" Version="6.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="6.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.10" PrivateAssets="all" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="6.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="6.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
		<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0" />
		<PackageReference Include="Microsoft.Extensions.Identity.Core" Version="6.0.10" />
		<PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="6.0.10" />
		<PackageReference Include="Microsoft.Extensions.Localization" Version="6.0.10" />
		<PackageReference Include="Microsoft.TypeScript.MSBuild" Version="4.8.4">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="System.Net.Http.Json" Version="6.0.0" />

	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Shared\ws4.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Content Update="wwwroot\images\bin_blacklist.svg">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\images\bin_gft.svg">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\images\bin_noread.svg">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\images\bin_papier.svg">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\images\bin_pmd.svg">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\images\bin_rest.svg">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\images\bin_unknown.svg">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\images\ImageMissing.png">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\images\van_all.svg">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\images\van_offline.svg">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\images\van_online.svg">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\leaflet\leaflet-geoman.css">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\leaflet\leaflet-geoman.min.js">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\fontawesome\webfonts\" />
	</ItemGroup>

</Project>

My Program.cs looks like:
```
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.Services
                  .AddBlazorise(options =>
                  {
                      options.Debounce = true;
                      options.DebounceInterval = 300;
                  })
                  .AddBootstrap5Providers()
                  .AddFontAwesomeIcons();

            builder.RootComponents.Add<App>("#app");
            builder.Services.AddBlazoredSessionStorage();
            builder.Services.AddBlazoredLocalStorage();
            builder.Services.AddBlazorContextMenu();
            builder.Services.AddLocalization();

            builder.Services.AddOptions();
            builder.Services.AddAuthorizationCore();
            builder.Services.AddScoped<IdentityAuthenticationStateProvider>();
            builder.Services.AddScoped<AuthenticationStateProvider>(s => s.GetRequiredService<IdentityAuthenticationStateProvider>());
            builder.Services.AddScoped<IAuthorizeApi, AuthorizeApi>();
            builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

            //            builder.Services.AddMemoryCache();
            builder.Services.AddScoped<ResizeListener>();
            builder.Services.AddAutoMapper(AppDomain.CurrentDomain.GetAssemblies());
            builder.Services.AddScoped<FrontendDataService>();
            builder.Services.AddScoped<FrontendMaintenanceDataService>();

            builder.RootComponents.Add<HeadOutlet>("head::after");

            builder.Services.AddResizeListener(options =>
            {
                options.ReportRate = 300;
                options.EnableLogging = true;
                options.SuppressInitEvent = true;
            });

            var host = builder.Build();

**Comment by stsrki** [comment] 2022-11-21 10:52
Did you try `1.1.3.1` while still targeting NET 6?

**Comment by David-Moreira** [comment] 2022-11-21 23:22
Hello,

WebAssembly + 1.3.1 + Net 6
![image](https://user-images.githubusercontent.com/22283161/203177511-ce93185e-d67d-451f-aa35-4152e6467ce5.png)
![image](https://user-images.githubusercontent.com/22283161/203177671-5c3f0319-8410-464e-b64e-320e362c6b2d.png)

WebAssembly + 1.3.1 + Net 7
![image](https://user-images.githubusercontent.com/22283161/203177335-cd086e76-b21e-4447-81c7-cb00c1f490e3.png)
![image](https://user-images.githubusercontent.com/22283161/203177459-b2879071-c555-4630-9aa7-515438eb15ac.png)



Both working fine, can you provide a repro with the actual error? My guess is that we'd have alot more complaints if latest version would just straight up not work.

**Comment by stsrki** [comment] 2022-11-22 07:41
In the OP error log( in the image ), it is mentioning AutoMapper. Maybe AutoMapper is the reason for the error?

**Comment by tacoWanneeJama** [comment] 2022-11-22 08:42
That's correct. When I remove dependances for AutoMapper the error disappears.
So apparently it is a conflict with Automapper.
I use packages:
```
<PackageReference Include="AutoMapper" Version="12.0.0" />
<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
```

**Comment by stsrki** [comment] 2022-11-22 08:46
@David-Moreira, what do you think we move all artefacts from `Blazorise.Generator.Features` to the core `Blazorise` project? They're just a few attributes anyways. And we will not worry about this kind of problem.

**Comment by David-Moreira** [comment] 2022-11-22 22:04
Did we not talk that the private="all" would solve this? It's a strange conflict that one. I haven't investigated.

The Generator would have to pull Blazorise as a dependency or just check for the attributes by string comparision. If you're ok with any of these, we could.

**Comment by stsrki** [comment] 2022-11-23 06:35
Let's discuss it further. private="all" should work, but if it keeps happening, we will need to remove `Blazorise.Generator.Features`.

**Comment by tacoWanneeJama** [comment] 2022-12-05 07:30
Do you expect answer?

**Comment by stsrki** [comment] 2022-12-05 10:10
1.1.4.1 was released already, and not one reported an issue regarding this. So I think we can close this ticket.

**Comment by tacoWanneeJama** [comment] 2022-12-21 09:35
Do you expect some input from me?

**Comment by stsrki** [comment] 2022-12-21 10:13
> Do you expect some input from me?

Nop :)

**Comment by TacoWannee** [comment] 2023-01-20 10:05
I still get the same error when I use the latest version:

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not load file or assembly 'Blazorise.Generator.Features, Version=1.1.6.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
System.IO.FileNotFoundException: Could not load file or assembly 'Blazorise.Generator.Features, Version=1.1.6.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Blazorise.Generator.Features, Version=1.1.6.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.CustomAttribute.GetCustomAttributesBase(ICustomAttributeProvider obj, Type attributeType, Boolean inheritedOnly)
   at System.Reflection.CustomAttribute.GetCustomAttributes(ICustomAttributeProvider obj, Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type attributeType)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes(MemberInfo element, Type attributeType)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[AutoMapAttribute](MemberInfo element)
   at AutoMapper.MapperConfigurationExpression.AddMapsCore(IEnumerable`1 assembliesToScan)
   at AutoMapper.MapperConfigurationExpression.AddMaps(Assembly[] assembliesToScan)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.<>c__DisplayClass12_0.<AddAutoMapperClasses>b__6(MapperConfigurationExpression options)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1[[AutoMapper.MapperConfigurationExpression, AutoMapper, Version=12.0.0.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005]].Configure(String name, MapperConfigurationExpression options)
   at Microsoft.Extensions.Options.OptionsFactory`1[[AutoMapper.MapperConfigurationExpression, AutoMapper, Version=12.0.0.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005]].Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1[[AutoMapper.MapperConfigurationExpression, AutoMapper, Version=12.0.0.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005]].get_Value()
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.<>c.<AddAutoMapperClasses>b__12_2(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Func`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IConfigurationProvider](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.<>c.<AddAutoMapperClasses>b__12_3(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeServiceProviderEngine.<>c__DisplayClass4_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass7_0.<CreateInitializer>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

**Comment by TacoWannee** [comment] 2023-01-20 10:51
Yes, all to the latest version

**Comment by tacoWanneeJama** [comment] 2023-01-26 07:52
Are there plans to solve this issue?

**Comment by stsrki** [comment] 2023-01-26 09:17
From our side, the issue is already solved. We would need a way to reproduce it to fix if any issue is still left.

**Comment by tacoWanneeJama** [comment] 2023-01-27 11:27
I have made a repository to show and reproduce the problem: [https://github.com/tacoWanneeJama/Automapper2.git](https://github.com/tacoWanneeJama/Automapper2.git)
I used a scaffolded Blazor application, where I added Blazorise and Automapper.
All is working OK for Blazorise 1.0.7, but when upgrading to 1.1.6 (last commit), the application gives the error when browsing to the Weatherforecast page.

**Comment by stsrki** [comment] 2023-01-27 11:53
I'm able to reproduce it now. Thanks for the project. It seems that AutoMapper cannot solve one of the generated types.

@David-Moreira can you look into this?

**Comment by TacoWannee** [comment] 2023-02-06 08:51
Maybe re-open this issue?
Or shall I make a new bug report?

**Comment by stsrki** [comment] 2023-02-06 08:53
@David-Moreira can you look into this?

> Maybe re-open this issue?
> Or shall I make a new bug report?

no need to open new issue :)

**Comment by tacoWanneeJama** [comment] 2023-02-06 08:55
Thanks

**Comment by David-Moreira** [comment] 2023-02-10 18:39
Hello @TacoWanneeJama

I was taking a look at this,
why are you throwing every single assembly into automapper? 

![image](https://user-images.githubusercontent.com/22283161/218170820-02160d25-7872-41f5-b892-2fa2ef8ed854.png)

I don't see any reason why you would other then being lazy. :)
I don't see it being recomended on Automapper's docs either.

Would it not be wiser to only provide the Assembly where Automapper should search for the Profiles?

https://docs.automapper.org/en/stable/Dependency-injection.html

So in your example it could be something like : 
`builder.Services.AddAutoMapper( typeof( Automapper2.Shared.MapperProfile ) );`
Let us know if this helps.

**Comment by VaclavElias** [comment] 2023-02-12 13:19
I have just started using Blazorise and get similar problem.

I have fixed it by adding a package

 `<PackageReference Include="Blazorise.Generator.Features" Version="1.2.0" />`.

![image](https://user-images.githubusercontent.com/4528464/218313412-827c6afd-417c-4442-937d-f6599ba0b346.png)

**Comment by David-Moreira** [comment] 2023-02-12 14:35
Hmm I guess it's the same problem. You're scanning the Blazorise assembly with Automapper, the fix would be to just scan the proper assemblies. You don't need to scan the Blazorise assembly.

**Comment by VaclavElias** [comment] 2023-02-12 22:40
You are right. With this `services.AddAutoMapper(typeof(Program));` I removed the package and all is working. Thanks.

**Comment by tacoWanneeJama** [comment] 2023-02-13 08:37
That's I very good input. I had to change the suggested line to:
``` builder.Services.AddAutoMapper(typeof(Program), typeof(WebAssemblyHost), typeof(SharedMapperProfile));```
But that is the solution for me.
Thanks a lot you all.

**Comment by stsrki** [comment] 2023-02-13 10:16
Since @David-Moreira suggestion seems to work, should we close the ticket?

**Comment by David-Moreira** [comment] 2023-02-13 18:20
Going ahead and closing the ticket then.
It's indeed strange that `AutoMapper` tries to go into private defined assemblies. But Anyways, I believe `Blazorise` will never need to be scanned by `AutoMapper` for it to work properly as the purpose is to automatically find the AutoMapping Profiles in the scanned assemblies and register them.

**Closed by David-Moreira** 2023-02-13 18:20 UTC
Labels: Status: Expecting Answer
