### ISSUE TITLE
DatePicker bad Date selected when using DisplayFormat 

### ISSUE THREAD

**Issue by pkejval** [Megabit/Blazorise#3346] opened 2022-01-21 12:40 UTC
**Describe the bug & reproduce**

When using DatePicker where Date variable is DateTime.Now (2022-01-21) and selecting day 24 or 25 Date changes to 2022-01-24 and is displayed as "Pondělí 24.01.2022" as expected **but when DatePicker loses focus** Date jumps to 2025-08-01 and component shows "Pátek 01.08.2025"! My language is cs_CZ.

```
<DatePicker TValue="DateTime" Date="@Date" DateChanged=@(async (date) => { await LoadData(date); } ) DisplayFormat="dddd dd.MM.yyyy" FirstDayOfWeek="DayOfWeek.Monday"/>
```
When I ommit DisplayFormat property bug is not present anymore. Picked date stays at 2022-01-24 as expected.
```
<DatePicker TValue="DateTime" Date="@Date" DateChanged=@(async (date) => { await LoadData(date); } ) FirstDayOfWeek="DayOfWeek.Monday"/>
```

**Comment by stsrki** [comment] 2022-02-01 11:11
I cannot reproduce the issue. Might be something with localization. We recently fixed it #3283

What Blazorise version do you work with?

**Comment by pkejval** [comment] 2022-02-02 06:10
Blazorise version where I noticed bug is 0.9.5.4. And I'm using Blazorise.Bootstrap5 if it can be related.
I'll try with 0.9.5.5 and let you know.

**Comment by stsrki** [comment] 2022-02-16 13:54
Hi, @pkejval do you still have the problem?

**Comment by pkejval** [comment] 2022-02-16 13:59
Sorry, forgot to write here. Yes, problem is still present in 0.9.5.5

**Comment by stsrki** [comment] 2022-02-16 14:00
In that could you provide us with a small project to reproduce the issue?

**Comment by pkejval** [comment] 2022-02-16 14:05
Sure I will provide project.

In the meantime I found out when I use `DisplayFormat="dd.MM.yyyy dddd"` bug is not present anymore. Problem is present only when using `DisplayFormat="dddd dd.MM.yyyy"`.

**Comment by stsrki** [comment] 2022-02-16 14:12
I think I know what is the problem. You have missed to update the Date variable. This is needed for a two way binding to work,

```diff
<DatePicker TValue="DateTime" Date="@Date" DateChanged="@OnDateChanged" DisplayFormat="dddd dd.MM.yyyy" FirstDayOfWeek="DayOfWeek.Monday" />
@code {
    async Task OnDateChanged(DateTime date )
    {
+        Date = date;

        await LoadData(date);
    }

    DateTime Date;
}
```

**Comment by pkejval** [comment] 2022-02-17 09:29
I prepared minimal project for reproducing issue: https://github.com/pkejval/BugExample

You are right it's missing in https://github.com/Megabit/Blazorise/issues/3346#issue-1110427281 but in my production code I have `Date = date` in my LoadData function so it's not that problem. Please see example project.

**Comment by stsrki** [comment] 2022-02-17 10:17
I don't have access to https://github.com/pkejval/BugExample. Getting 404.

**Comment by pkejval** [comment] 2022-02-17 10:20
Try now please.

**Comment by stsrki** [comment] 2022-02-17 10:26
The provided project works without any issues for me 👀

**Comment by stsrki** [comment] 2022-02-17 10:45
I can reproduce it now. Although not all the time. It works about ~70% time.

**Comment by stsrki** [comment] 2022-02-19 13:06
Again cannot reproduce it. Been trying for the last 20 minutes.

**Comment by stsrki** [comment] 2022-03-06 12:32
Closing since we were unable to reproduce it.

**Closed by stsrki** 2022-03-06 12:32 UTC
Labels: Type: Bug 🐞
