### ISSUE TITLE
[Bug]: Setting the `ToolbarButtonClassPrefix` on the `Markdown` has no effect

### ISSUE THREAD

**Issue by linkdotnet** [Megabit/Blazorise#5879] opened 2024-12-04 19:29 UTC
### Blazorise Version

1.7.0

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction or a simple code snippet

Creating a component like this:
```html
<Markdown ToolbarButtonClassPrefix="test"/>
```

Has 0 effect on the classes that are applied.
![Image](https://github.com/user-attachments/assets/29ef6e9b-6dc2-4906-865a-288a2fdf2587)

### Steps to reproduce & bug description

See the example above

### What is expected?

Buttons should have the prefix - for example the table button should have the CSS class: `test-table`

### What is actually happening?

No prefix is applied.

**Comment by stsrki** [comment] 2024-12-04 19:39
Duplicate of #5876, as it is the same issue. Closing now.

**Closed by stsrki** 2024-12-04 19:39 UTC
Labels: Type: Bug 🐞
