### ISSUE TITLE
DataGrid: Improve nested DataGrid experience

### ISSUE THREAD

**Issue by Herdo** [Megabit/Blazorise#466] opened 2019-12-31 13:26 UTC
Currently we can nest several `DataGrid` components by adding them to the `ChildContent` of the parent's `DetailRowTemplate`. Basically, this works fine, but depending on the CSS framework, this causes issues.

For example, setting `IsStriped = true` on the parent `DataGrid` while using the Bootstrap framework causes the nested `DataGrid` to also be striped, even though that one has `IsStriped = false`.

The `DataGrid` components (and direct childs) should behave like configured, not how the CSS framework dictates it.

**Comment by stsrki** [comment] 2019-12-31 13:55
It seems this is by design for Bootstrap: https://stackoverflow.com/a/52862091/833106

You're right, this should not be possible. This needs to be defined for every possible table style.

**Comment by stsrki** [comment] 2024-08-05 08:32
Closing as we don't have plans for this feature.

**Closed by stsrki** 2024-08-05 08:32 UTC
