### ISSUE TITLE
Datagrid column sorting

### ISSUE THREAD

**Issue by Electriccc** [Megabit/Blazorise#2902] opened 2021-09-10 11:15 UTC
If datagrid is sorted by one column, all others are not working until you unsort the first sorted column.
Sorted column should reset and sort again for the second column clicked.

**Comment by David-Moreira** [comment] 2021-09-10 17:43
@Electriccc are you using single or multiple sorting? can you make sure you are not making confusion with multiple sorting? For multiple sorting you should be aware of sorting priority, as the columns will always be first sorted by the first sort column and only then by the next one. 

If you are still having difficulties, Send us a code example, please.

**Comment by Electriccc** [comment] 2021-09-10 18:58
Hi David,
This is the funcionality without multiple  sorting, multiple sorting means
that you can sort by multuple columns at the same time, this is without
that funcionality, if you sort by one column you are unable to cancel that
sort by sorting on another column you first need to click once or twice to
unsort first sorted column and then sort it with the second column. Tested
it and talked to Mladen about it and he said its a bug to report it, try it
out.

**Comment by stsrki** [comment] 2021-09-10 19:10
Yes, definitely a bug. When in single mode you should be able to sort by any column without unsorting currently sorted column.

**Comment by David-Moreira** [comment] 2021-09-19 10:38
@Electriccc  // @stsrki 
I was just going to start working on fixing this, but I cannot reproduce it.
Both on latest 0.9.4 branch and on live Blazorise Bootstrap Demo:
1- Navigate to DataGridPage
2- Set SortMode to Single
3- Sort by any column... for example: FirstName
4- Sort by any other column, for example: LastName

It correctly cancels the previous sort on FirstName and starts a new sort on LastName.
Am I doing the steps correctly or missing something? Can you please provide the correct steps so I can reproduce, thanks!

**Comment by David-Moreira** [comment] 2021-09-19 10:43
Oh wait... I was re-reading...
> When in single mode you should be able to sort by any column **without unsorting currently sorted column**.

this does not seem right? Are we sure it should work like this?? This is basically multiple sorting not single? Or am I missing something?

To me, Single means I can only sort by one column at a time... and generally I think Datagrids / Data Tables work like this, do they not?

**Comment by stsrki** [comment] 2021-09-19 10:56
When in the _single mode_ you and you click on the header to sort it needs to reset to ascending every time you click on another column. And if you click on the same column it will cycle _ascending, descending, none_

**Comment by David-Moreira** [comment] 2021-09-19 11:47
That's what happens already? 😆

**Comment by Electriccc** [comment] 2021-09-19 13:08
Hmm i will check again on Monday, but it didnt work in any way for me.

**Comment by stsrki** [comment] 2021-09-19 20:27
> That's what happens already? 😆

No, it isn't. If you go to the demo app you can reproduce it.

1. Click on First Name and see how the sort arrow is shown

![image](https://user-images.githubusercontent.com/900302/133941912-5ac26d35-32e3-4b37-bddc-170bf01b4cfc.png)

2. Now click on the Last name.

![image](https://user-images.githubusercontent.com/900302/133941943-168c3573-8cbe-4dc2-b065-84332dcdcd91.png)

It shows the sort for the by the Last Name, But it still leaves the icon for the First Name.

**Comment by David-Moreira** [comment] 2021-09-19 20:44
Hello,
Just went to https://bootstrapdemo.blazorise.com/tests/datagrid
and redid the steps I described above, cannot reproduce. O.o

Are you forgetting to set the Sort Mode to `Single`?

**Comment by stsrki** [comment] 2021-09-19 20:46
🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️

I was looking at Single here

![image](https://user-images.githubusercontent.com/900302/133942522-7745e78f-fcc6-46d8-b8cd-3f85c74c64a2.png)

😅

**Comment by stsrki** [comment] 2021-09-20 14:35
Closing because it is working as expected.

**Closed by stsrki** 2021-09-20 14:35 UTC
Labels: Type: Bug 🐞
