### ISSUE TITLE
[Bug]: Selected Row does not change when Rapid Editing 

### ISSUE THREAD

**Issue by mtbayley** [Megabit/Blazorise#5398] opened 2024-03-22 17:29 UTC
### Blazorise Version

1.5.0

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction or a simple code snippet

https://blazorise.com/docs/extensions/datagrid/features/editing

### Steps to reproduce

1. Select a row using the # column
2. Attempt to edit another cell by clicking on it

![image](https://github.com/Megabit/Blazorise/assets/34929316/1ad82a50-9612-4cee-9e56-ae26a30598c4)

### What is expected?

The selected row should change to the edited row if the row is selectable

### What is actually happening?

The row selected does not change

### What browsers do you see the problem on?

Microsoft Edge

### Any additional comments?

Sorry, I've submitted a lot of issues this week!

This may no longer be an issue if navigation and editing is separated as discussed in #5383. I wanted to bring this to your attention to consider.

**Comment by David-Moreira** [comment] 2024-03-22 17:49
Hello,

I'm not understanding how to reproduce,

1. https://blazorise.com/docs/extensions/datagrid/features/editing
2. First Grid, change to EditMode.Cell
3. Click Wilkinson Cell
4. Click the cell with the number 3, it will be selected but not editable, as the cell is not marked as editable
5. Click any other cell?

When I get to 5, when I click any other cell it is editable as expected?

**Comment by mtbayley** [comment] 2024-03-22 18:13
I'm looking at the selected row (the row that is highlighted). Editing is working as expected.
The only way to select it is to click on a cell that is not editable (# in this case).

Also, when I'm editing a cell, I can't see which row I have selected.

Perhaps this gif adds more context
![msedge_nq2vSEPEYb](https://github.com/Megabit/Blazorise/assets/34929316/30f0a218-977a-4563-87a4-6584e0f53900)

**Comment by David-Moreira** [comment] 2024-03-22 23:28
Hmm I see, so your point is that cell clicks aren't triggering row selection, this kind of is by design. 
If you use the command column to trigger a row edit, same thing happens, the row is in edit mode even though it's not selected.

Now the thing here, is that you are explicitly clicking on something inside the row, so it's argueable whether it should select the row or not. 
But the thing is that this is "cell mode", so imagining that we do trigger RowClick & Selection Changed here, does it really make sense?

The DataGrid always worked like this where the row being edited does not show the "selection look".

 @stsrki any opinion on this?

**Comment by stsrki** [comment] 2024-03-23 10:40
I think selecting the row by the last focused cell makes the most sense. Be it in read or edit mode.

**Comment by David-Moreira** [comment] 2024-03-26 23:04
In that case let's treat this as a bug. It will be fixed in v1.5.

**Closed** 2024-03-27 08:42 UTC
Labels: Type: Bug 🐞
