### ISSUE TITLE
NumericEdit Min not respected in any of the preview versions

### ISSUE THREAD

**Issue by sturlath** [Megabit/Blazorise#3490] opened 2022-02-21 19:51 UTC
This doesn´t do anything, any number higher/lower works. I tried all the preview versions on a none-abp.io :-)

`xml
<NumericEdit  Min="600"  />
`

**Comment by stsrki** [comment] 2022-02-22 06:24
Can you try the new `NumericPicker` component? All of the features from `NumericEdit` are now part of it. And even more. The purpose of `NumericEdit` is now to behave like a native `input type="number"` element.

**Comment by sturlath** [comment] 2022-02-22 08:53
Ok that almost works so great!

I can´t get rid of the trailing zeros (Kr.500**.00** in the case below) even though I am just using int and trying to control it with various settings (Decimals etc)


``` xml
<NumericPicker TValue="int" TValue="int" Step="10" CurrencySymbol="Kr." Decimals=0  @bind-Value="@NewStreamEvent .MinPrice" Min="@minStreamingPrice"  />
```  
and

```csharp
private StreamEvent NewStreamEvent { get; set; }
private int minStreamingPrice{ get; set; }

protected override async Task OnInitializedAsync()
{
   NewStreamEvent = await GetEvent();
   minStreamingPrice = NewStreamEvent .MinPrice;
}
```

It looked like `AllowDecimalPadding` was what I was looking for, and [the Description says](https://preview.blazorise.com/docs/components/numeric-picker) I could set it to 'false' but thats not possible.

What am I missing?

**Comment by sturlath** [comment] 2022-02-22 08:56
Ah... `AllowDecimalPadding` is probably the abp.io issue.. new enum... because now I don´t see any 'false'.. is that it?

**Comment by stsrki** [comment] 2022-02-22 10:05
It is not an ABP enum, but Blazorise's. The parameters that control decimals are `RoundingMethod` and `AllowDecimalPadding`.

Or do you want to control the numbers on the left side of the separator?

**Comment by stsrki** [comment] 2022-02-22 10:08
Maybe `leadingZero` is what you want? Check here https://github.com/autoNumeric/autoNumeric/

If yes, I can make it fast I think.

**Comment by stsrki** [comment] 2022-02-22 10:50
![image](https://user-images.githubusercontent.com/900302/155117424-21a0cd2a-ca8e-4ed8-817b-e3516a730e8b.png)

That indicated that it would work.

**Comment by sturlath** [comment] 2022-02-22 11:03
Are you saying AllowDecimalPadding.Never should work according to the their docs? I have at least tried various versions and I can´t get it to skip `.00` and can´t think of anything else to try out.

**Comment by stsrki** [comment] 2022-02-22 11:12
Maybe it's a bug then :(

**Comment by stsrki** [comment] 2022-03-11 06:05
This should be fixed in latest 1.0.1. There was a problem with NumericPicker value not being properly synchronized with autoNumeric. I have fixed it.

@sturlath I will close now and if error persist just reopen.

**Closed by stsrki** 2022-03-11 06:06 UTC
Labels: Type: Bug 🐞

**Comment by WolfgangKluge** [comment] 2022-05-27 01:02
Maybe you want to update the docs (and remove the `[Parameter]`s for `Min` and `Max`) if you don't want to support that

**Comment by samywang92** [comment] 2022-07-01 16:45
Hello Blazorise team,

I agree with @WolfgangKluge's statement.  I came across this bug as well thinking that Numeric Edit wasn't working as intended.  I think the documentation should be updated to remove `Min` and `Max` and also let users know its supported on `NumberPicker` instead.

Thank you for fixing all the issues related to the picker tho! :)
