### ISSUE TITLE
Refactor closable components

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#2551] opened 2021-07-01 09:49 UTC
Affected components

- Modal
- Dropdown
- BarDropdown
- Select (AntDesign)

Currently, all our closable components are tracked using the JS once they are in an `open` state. The component will close if it loses focus or the user press `Escape` key. What is problematic is how we detect lost focus. We do it by checking elementId, from the opened component and the one we clicked on. With this, it is impossible to do any nesting of the closable components.

The only way to fix is to refactor the entire code and implement some new way of opening and closing states.

Once done it should fix

- #2138 Escape key in Autocomplete component closes Modal
- #1559 Nested Dropdowns malfunctioning

**Comment by stsrki** [comment] 2021-07-01 10:03
@David-Moreira any help or suggestion regarding this problem is welcome. I have tried looking at other projects and guys at BlazorStrap have an interesting approach for toggleable components.

**Comment by David-Moreira** [comment] 2021-07-02 14:08
No opinion yet. I'll have to take a look at the current implementation. Assigning to myself just so I can keep track/remember to give feedback.

**Comment by David-Moreira** [comment] 2021-07-03 16:27
Hello,
I just took a brief look at #2138 
I see you straight up just bind the key up event listener to the document. Would it be different to bind to the closeable component instead?

Also, the event, despite bubbling from children, does bring the source element that called it. Would that not be a way to handle this? Make sure the src element is the closeable element?

**AutoComplete:**
![image](https://user-images.githubusercontent.com/22283161/124360717-1d642300-dc23-11eb-8c65-a3e5c4a7d62d.png)

**Modal:** 
![image](https://user-images.githubusercontent.com/22283161/124360720-205f1380-dc23-11eb-848f-e7c35cb47e0b.png)

... Oh in the meantime I just saw re-read what you wrote... so while for the escape key, this could be a solution? Right? It seems that's what you're already doing in the other case actually...

So the problem is the focus... Well, you could probably maintain the same implementation, but implement "dependencies"... Meaning that if a certain closeable component has another dependency with another closeable component, it might not be closed, while the other is not closed. Does that make sense?

But like we've talked before. We should just get together and brainstorm about this later.

**Comment by stsrki** [comment] 2021-07-03 16:30
Yeah, dependencies are the real problem. For modal for example a dependency is the backdrop. For dropdown, it can a menu or a toggle button. And if we have nested dropdown menus it can easily get complicated.

**Comment by DezareD** [comment] 2021-09-03 17:39
I don’t know, maybe this will somehow help, but if you wrap the DropdownMenu with the form tag, then the first time you click on DropDown, it will close, but if you do it again (open DropDown and click on it), it will not close.

**Closed** 2021-09-27 13:13 UTC
Labels: Type: Refactoring 🧹
