### ISSUE TITLE
TimeEdit with TimeSpan throws FormatException

### ISSUE THREAD

**Issue by faarbaek** [Megabit/Blazorise#2460] opened 2021-06-09 18:31 UTC
**Describe the bug**
After upgrading to 0.9.3.7, the TimeEdit component does not work with TimeSpan. I'm getting a FormatException with the message "Input string was not in a correct format".

**To Reproduce**
Define a TimeEdit tag with TValue="TimeSpan"

**Expected behavior**
TimeSpan value gets correct formatted in TimeEdit component

When downgrading to 0.9.3.6 the TimeEdit with TimeSpan type works fine.

**Comment by stsrki** [comment] 2021-06-09 20:47
Hi, thanks for reporting it. The issue is a duplicate of #2437 and is already fixed.

I have just now released new nuggets so you should be able to get them.

**Closed by stsrki** 2021-06-09 20:47 UTC
