### ISSUE TITLE
Blazor App stuck in Chrome mobile after installing  Blazorise.Bootstrap

### ISSUE THREAD

**Issue by bodeg** [Megabit/Blazorise#2448] opened 2021-06-04 04:10 UTC
Hi
1. I created a fresh Blazor Webassembly App (VS 2019)
2. Target Framework: net 5.0
3. Checked the "ASP.NET Core hosted"
4. Published it to Azure
5. It works fine...

Now..
1. I installed Blazorise.Bootstrap package in the Client project
2. That's it!
3. Published it again to Azure

On my desktop - the Blazor app works fine.

BUT,
On my mobile (Android) - using the latest version of Chrome - it stuck on the "Loading...".
Chrome 91.0.447288

Also 1, I "Uninstall updates" for the Chrome, and it works.  
Also 2, On mobile the Blazor app works fine in Edge, Firefox and Brave.

What am I doing wrong?

**Comment by stsrki** [comment] 2021-06-04 09:30
You only installed NuGet package? Or did you also configured everything line in our setup guide?

Not sure why it would not work. I have a bunch of apps running on IIS without a problem. Maybe Azure has something different. The only thing that comes to mind is an option I had to disable. In App.razor, remove `PreferExactMatches`.

**Comment by bodeg** [comment] 2021-06-04 10:11
I just installed the NuGet package. nothing more!

Just to make clear: it works fine on Azure when I on the desktop.
Also, it works on Azure on the mobile when I am using Edge, Firefox or Brave.

The only problem is with latest version of Chrome on the mobile.
And I tried it on different phones.

Also, I removed PreferExactMatche - still have the same problem.

you may try:
https://lmiwebappserver.azurewebsites.net/

**Comment by Jimmys20** [comment] 2021-06-04 15:18
I tried your link and it works fine on my android phone using Chrome version 90.0.4430.210. Maybe try to clear the browser cache?

**Comment by bodeg** [comment] 2021-06-04 16:49
I followed Jimmys20's comment, and downgraded my Chrome to 90.0.4430.210 - and it works.
But then, I updated the Chrome to 91.0.4472.88 - and it stuck in "Loading..."

I also, cleared the browser cache many times...

**Comment by tesar-tech** [comment] 2021-06-13 10:31
@bodeg I also have this. Mobile chrome is unable to pass loading screen. Fresh, clean installation of chrome. Brave is fine. FF is fine.

**Comment by Jimmys20** [comment] 2021-06-13 10:53
https://developer.chrome.com/docs/devtools/remote-debugging/

**Comment by tesar-tech** [comment] 2021-06-13 11:02
@Jimmys20 I tried. While usb-debugging the page loads without an issue, when I disconnect the phone from computer is just does not work anymore. Weird, I know..

**Comment by bodeg** [comment] 2021-06-14 07:32
I checked the remote debugging when I first found the problem, I had the same behavior as @tesar-tech described.
I think - when using remote debugging you are going through the desktop Chrome...

The "good" news - I tried Chrome Beta (mobile version) 92.0.451.40 - and it works...

**Comment by aarrtturas** [comment] 2021-06-14 17:29
I have the same problems with my app. On mobile android Opera, Firefox, Edge - works fine, on old Chrome - works fine. On Chrome 91.0.4472.101 (Official Build) (64-bit) it is not loading. The same issue. It it somehow related to Chrome version, but depends on NuGet packages as well. Very unexpected behavior. In debug mode in console no errors, it just hangs and waits for something. I noticed more or less the same behavior on desktop Chrome and Edge - first time load (after history cleaned) it takes about 30 seconds. And all later times it loads in 4 s.

**Comment by tesar-tech** [comment] 2021-06-15 19:45
One more piece of the puzzle: I let my app to output all requested paths to console:

```csharp
// Configure method in Startup class of server project:
pp.Use(async(context, next) =>
{
Console.WriteLine($"{context.Request.Path.Value}");
 await next();
}
```

## When requested from mobile chrome:
```
2021-06-15T19:41:50.458327642Z: [INFO]  /_framework/blazor.webassembly.js 
2021-06-15T19:41:50.609395246Z: [INFO]  /_framework/blazor.boot.json 
2021-06-15T19:41:50.696703675Z: [INFO]  /_framework/dotnet.5.0.4.js 
```
(that's all, nothing more)

## When requested from desktop chrome:
```
2021-06-15T19:43:02.149170013Z: [INFO]  / 
2021-06-15T19:43:02.221995493Z: [INFO]  /css/app.min.css 
2021-06-15T19:43:02.235309690Z: [INFO]  /_framework/blazor.webassembly.js 
2021-06-15T19:43:02.293429574Z: [INFO]  /_framework/blazor.boot.json 
2021-06-15T19:43:02.369606053Z: [INFO]  /_framework/dotnet.5.0.4.js 
2021-06-15T19:43:03.432366569Z: [INFO]  /_configuration/BlazorApp6.Client 
2021-06-15T19:43:03.617090320Z: [INFO]  /.well-known/openid-configuration 
```
...and much more files..

**Comment by Jimmys20** [comment] 2021-06-15 22:20
It seems that this problem is not related to Blazorise. For some reason Blazor is not working correctly on version 91.0.4472.101 of Chrome for android. Check [https://github.com/dotnet/aspnetcore/issues/33559](https://github.com/dotnet/aspnetcore/issues/33559).

**Comment by tesar-tech** [comment] 2021-06-15 22:57
Don't forget to upvote that issue!

**Comment by stsrki** [comment] 2021-06-18 10:42
Should I close this ticket since problem is in chrome version?

**Comment by David-Moreira** [comment] 2022-03-11 00:00
Hopefully this no longer happens nowadays as we no longer had complaints. Closing issue.

**Closed by David-Moreira** 2022-03-11 00:00 UTC
