### ISSUE TITLE
datagrid begin edit

### ISSUE THREAD

**Issue by ehsangfl** [Megabit/Blazorise#2785] opened 2021-08-06 13:24 UTC
if entity has an complex property with no default constructor, this exception will thrown

`Default constructor not found for type [complex type]`
stack trace is 
```

at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Blazorise.DataGrid.Utils.RecursiveObjectActivator.CreateInstanceRecursive(Object currObjInstance, PropertyInfo[] properties)
   at Blazorise.DataGrid.Utils.RecursiveObjectActivator.CreateInstanceRecursive(Object currObjInstance, PropertyInfo[] properties)
   at Blazorise.DataGrid.Utils.RecursiveObjectActivator.CreateInstance[Tbl_AST_EstateOwnership]()
   at Blazorise.DataGrid.DataGrid`1[[AppModel.Web.Model.Tbl_AST_EstateOwnership, Sayeh.AppModel, Version=1.0.0.2, Culture=neutral, PublicKeyToken=null]].InitEditItem(Tbl_AST_EstateOwnership item)
```
blazorise version : 9.4.2

**Comment by stsrki** [comment] 2021-08-06 13:30
Can you try the latest 0.9.4.3 preview? This problem should be fixed.

https://github.com/Megabit/Blazorise#try-preview

Let us know how it goes.

**Comment by David-Moreira** [comment] 2021-08-08 12:58
Hello @ehsangfl 
Datagrid now uses an activator that generates a dummy object for validation purposes behind the scenes. So you should be providing a complex object with parameterless constructor so that it can be generated internally.

We'll be taking a look at this in the future, providing better usage / making it better documented.

**Comment by ehsangfl** [comment] 2021-08-08 14:02
@David-Moreira some types (like spatial types) does not have constructor. additionally, all of my entities inherited from base class, wich has internal/with-parameter cunstructor property type. I cannot wrap all entities inside an complex object with parameterless constructor. I think dummy object is not good solution for validation purpose. I think if you use IEditableObject and its implementation is better to create dummy object. another problem on dummy object is relational ORM. when navigation properties setted, the dummy object may be to added to context by change tracker mechanism

**Comment by David-Moreira** [comment] 2021-08-08 15:51
@ehsangfl thank you for raising the concern about spatial types.

I understand if your current implementation does not allow you to implement a parameterless constructor, which I can only advise you to use DTOs if at all possible.

Also thank you for the suggestion about IEditableObject, but I don't think it fits this use case, correct me if you think I'm wrong. Datagrid already implements it's own way of handling editable functionality, including edit init, rollback, edit end... 

As for the concern with the relation orm I don't see that happening, and it being picked up by the orm... Unless the user has some very specific logic on the constructor... Which he should be very aware of doing it this way... again correct if I'm wrong. 

As an example, even a relation orm like EF Core has to do some magic internally with parameterless constructors... And will complain if you don't provide it. 

We will be taking a look at this and as soon as we have news we'll let you know, but we do appreciate the tips and feedback, thank you.

**Comment by stsrki** [comment] 2021-08-09 07:21
I agree with @David-Moreira, you should be using DTOs, or other domain models, for the DataGrid data items, not the entity models directly.

Regarding the IEditableObject, it is not an option for several reasons. For example, it would force all our users to inherit their models from IEditableObject. Then since we already have our own editing logic it would take too many resources to refactor and I'm not sure it is worth it. Lastly, Blazor validation doesn't work with IEditableObject, although it probably isn't a real problem.

**Comment by ehsangfl** [comment] 2021-08-09 07:22
@David-Moreira  thank for your response and sorry about my week language.
I think this is a miss understanding. All of my entities have parameterless constructor. this problem is for some properties of entity that does not have parameterless constructor.
like this

```
public class A
{
public int ID {get;set;}

public B Property {get;set;}
}

```
source of datagrid is list of A

B is not another entity. B is some class like Spatial types. this error happen when entity has property as type that has not parameterless constructor.

when I begin edit on datagrid, datagrid thrown exception for B have not parameterless constructor

**Comment by StefanOssendorf** [comment] 2021-08-09 08:51
With the current limitation you should remove the `NewItemCreator` delegate to create a new item. Because this let a user believe he can use any kind of type without the need of a default constructor.
Furthermore a DTO must not always have a default ctor. For example I'm now using shallow wrappers to get rid of type incompability (see #2772) where I have a clas like this:
```csharp
class UIFoo {
private Foo _item;
 public Int32 {
    get => _item.Value1;
    set => _item.Value1 = EnsureInByteRange(value);

    public UIFoo(Foo item) { _item = item}
}
```
This would become much more complex and time consuming instead of wrapping it in that way.

**Comment by ehsangfl** [comment] 2021-08-09 08:58
@stsrki Thanks for your answer. as I described in previouse comment,
the problem is not an entity that has not parameterless constructor. all of my DTO has parameterless constructor.
the problem is when entity, have a property which this property type, has not parameterless constructor.
like this

```
public class Entity
{
public int ID{get;set;}

poblic Geography Point{get;set;}
}

```
in this case, Entity class has parameterless constructor, but Geography type (typeof point property inside entity) has not parameterless constructor. we cannot edit Entity class by blazorise.datagrid cause of point property

**Comment by David-Moreira** [comment] 2021-08-09 09:30
Hello @StefanOssendorf
NewItemCreator should work as you'd expect. Just that you are hitting an exception caused by this issue which is also related with activating object instances internally.

**Comment by stsrki** [comment] 2021-08-09 09:32
`NewItemCreator` is not called in this case. I'm now testing to see if it makes sense to use it for validation items.

**Comment by StefanOssendorf** [comment] 2021-08-09 09:34
Hi @David-Moreira 
Yes you are right (I created a dup at #2792). But with this the "should have a default ctor" isn't enforced any more. So removing this extension point and only using the InitNewItem would make that clear.

@stsrki 
Using the deleagte for the validation items does not make sense. For example I'm creating temporary Ids on creation of the item. With the usage for the validation item I would have gaps in my Ids. (In my case I don't care but could also be other stuff).

**Comment by stsrki** [comment] 2021-08-09 09:39
@StefanOssendorf I'm just experimenting at the moment. I agree, NewItemCreator doesn't make sense in this case since we're not creating a new item. We're creating an internal object that users should not be aware of.

So far this is promising(https://stackoverflow.com/questions/390578/creating-instance-of-type-without-default-constructor-in-c-sharp-using-reflectio) but now I'm facing another problem with accessing the nested fields when they are null.

I will keep you posted!

**Closed** 2021-08-10 08:09 UTC
Labels: Area: DataGrid
