### ISSUE TITLE
Modal not Modal

### ISSUE THREAD

**Issue by GilShalit** [Megabit/Blazorise#2537] opened 2021-06-29 08:56 UTC
V 0.9.3.9

Using the sample in the Modal documentation, clicking the button opens a Modal dialog.  But while the dialog is still open, if I click on the page behind it becomes active and I can interact with it while the dialog is hidden behind.  For example, I can click menu items in a shared MainLayout.razor.

Is that the expected behavior? 

```
<Modal @ref="modalRef">
    <ModalContent Centered="true">
        <ModalHeader>
            <ModalTitle>Employee edit</ModalTitle>
            <CloseButton />
        </ModalHeader>
        <ModalBody>
            <Field>
                <FieldLabel>Name</FieldLabel>
                <TextEdit Placeholder="Enter name..." />
            </Field>
            <Field>
                <FieldLabel>Surname</FieldLabel>
                <TextEdit Placeholder="Enter surname..." />
            </Field>
        </ModalBody>
        <ModalFooter>
            <Button Color="Color.Secondary" Clicked="@HideModal">Close</Button>
            <Button Color="Color.Primary" Clicked="@HideModal">Save Changes</Button>
        </ModalFooter>
    </ModalContent>
</Modal>
@code {
private Modal modalRef;
    private void ShowModal()
    {
        modalRef.Show();
    }

    private void HideModal()
    {
        modalRef.Hide();
    }
}
}
```

**Comment by stsrki** [comment] 2021-06-29 08:58
You don't get the modal backdrop when the modal is opened?

**Comment by stsrki** [comment] 2021-06-29 09:00
Maybe you're missing some CSS or JS files. Can you post the content of `index.html` or `_Host.cshtml` files?

**Comment by GilShalit** [comment] 2021-06-29 09:11
What do you mean by backdrop?

```
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>EconInteract</title>
    <base href="/" />
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="css/app.css" rel="stylesheet" />
    <link href="CrudAuthClient5.styles.css" rel="stylesheet" />
    <link href="manifest.json" rel="manifest" />
    <link rel="apple-touch-icon" sizes="512x512" href="icon-512.png" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
    <link href="_content/Blazorise/blazorise.css" rel="stylesheet" />
    <link href="_content/Blazorise.Bootstrap/blazorise.bootstrap.css" rel="stylesheet" />
    <link href="_content/Blazorise.DataGrid/blazorise.datagrid.css" rel="stylesheet" />
</head>

<body>
    <div id="app">Loading...</div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="_content/Blazorise.DataGrid/blazorise.datagrid.js"></script>

    <script src="_content/Blazorise/blazorise.js"></script>
    <script src="_content/Blazorise.Bootstrap/blazorise.bootstrap.js"></script>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
    <script src="_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js"></script>
    <script src="_framework/blazor.webassembly.js"></script>
    <script>navigator.serviceWorker.register('service-worker.js');</script>
</body>

</html>
```

**Comment by stsrki** [comment] 2021-06-29 09:33
Backdrop is grey area around the modal

![image](https://user-images.githubusercontent.com/900302/123774605-da761880-d8cd-11eb-89f6-fcbcdd368dc8.png)

**Comment by GilShalit** [comment] 2021-06-29 09:37
It becomes gray but is clickable, even while dialog is open.

**Comment by stsrki** [comment] 2021-06-29 09:37
You have duplicate bootstreap CSS. Also, reorder other like I noted

```diff
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>EconInteract</title>
    <base href="/" />
-    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
-    <link href="css/app.css" rel="stylesheet" />
-    <link href="CrudAuthClient5.styles.css" rel="stylesheet" />
    <link href="manifest.json" rel="manifest" />
    <link rel="apple-touch-icon" sizes="512x512" href="icon-512.png" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
    <link href="_content/Blazorise/blazorise.css" rel="stylesheet" />
    <link href="_content/Blazorise.Bootstrap/blazorise.bootstrap.css" rel="stylesheet" />
    <link href="_content/Blazorise.DataGrid/blazorise.datagrid.css" rel="stylesheet" />
+    <link href="css/app.css" rel="stylesheet" />
+    <link href="CrudAuthClient5.styles.css" rel="stylesheet" />
</head>

<body>
    <div id="app">Loading...</div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
-    <script src="_content/Blazorise.DataGrid/blazorise.datagrid.js"></script>

    <script src="_content/Blazorise/blazorise.js"></script>
    <script src="_content/Blazorise.Bootstrap/blazorise.bootstrap.js"></script>
+    <script src="_content/Blazorise.DataGrid/blazorise.datagrid.js"></script>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
    <script src="_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js"></script>
    <script src="_framework/blazor.webassembly.js"></script>
    <script>navigator.serviceWorker.register('service-worker.js');</script>
</body>

</html>
```

**Comment by stsrki** [comment] 2021-06-29 09:39
PS. It's best to update to latest bootstrap 4.6.x. I had some problems with 4.5.0 CDN

https://getbootstrap.com/docs/4.6/getting-started/introduction/

**Comment by GilShalit** [comment] 2021-06-29 11:13
I have
- made the changes above
- updated to 4.6
- cleared the cache

And still I get a dark backdrop but I can click it and have the dialog go to the back and the main page becomes active.

I take it you cannot reproduce?

**Comment by stsrki** [comment] 2021-06-29 11:14
No, everything works as expected on my side. Can you take the screenshot of your modal dialog?

**Comment by GilShalit** [comment] 2021-06-29 11:23
![image](https://user-images.githubusercontent.com/34002589/123789101-752e2180-d8e5-11eb-95b8-de1ec7fb8fbd.png)

**Comment by stsrki** [comment] 2021-06-29 11:34
Looks good to me.

I re-read your message and I'm not sure what you meant with

>  if I click on the page behind it becomes active and I can interact with it while the dialog is hidden behind

---

When you click on the backdrop, the dialog will close, but it will still stay in the DOM. That is by design. If you want to prevent closing of modal you can use the `Closing` event, eg. https://blazorise.com/docs/components/modal/#closing

**Comment by GilShalit** [comment] 2021-06-29 11:47
Isn't a modal dialog supposed to prevent the main page from being interactive while it is open?

I did ask if that is the expected behavior :-)

Will try the ```Closing``` event

**Comment by stsrki** [comment] 2021-06-29 11:55
Yeah, it shouldn't be able to interact with the main page.

But it's hard to tell what is wrong unless I can reproduce it on my side.

**Comment by David-Moreira** [comment] 2021-06-29 11:59
@GilShalit would you be so kind as to set up a repository with the problem, so we can replicate / test ourselves? :)

**Comment by GilShalit** [comment] 2021-06-29 13:00
Will do

**Comment by stsrki** [comment] 2021-07-20 12:31
@GilShalit Any chance you could provide us with a minimal example to reproduce the problem? Thanks

**Comment by GilShalit** [comment] 2021-07-21 10:53
yes, i will do it today or tomorrow.

**Comment by GilShalit** [comment] 2021-07-28 15:09
Ouch, sorry, that took longer then I planned...

The repo is at https://github.com/GilShalit/ModalRepo.  The behavior is the same after upgrading to 0.9.4.1 .

Thanks for the awesome project!!!

**Comment by stsrki** [comment] 2021-07-28 21:12
@GilShalit I tried your project and I don't see a problem with it. The expected behavior for Modal is to close when you click on the backdrop. And also, Modal is always present in the DOM, otherwise, it would not be able to react to any action like `Show` or `Hide`.

I have once again read your messages, and maybe you want to prevent the modal from closing? If that is the case then you only need to react to the `Closing` event, https://blazorise.com/docs/components/modal/#closing

Example

```cshtml
<Modal @ref="modalRef" Closing="@OnModalClosing">
    ...
</Modal>
@code{
    // reference to the modal component
    private Modal modalRef;

    private void OnModalClosing( ModalClosingEventArgs e )
    {
        // just set Cancel to true to prevent modal from closing
        e.Cancel = e.CloseReason == CloseReason.FocusLostClosing;
    }
}
```

**Comment by GilShalit** [comment] 2021-07-29 10:05
Got it - works fine obviously.  I was thrown by your comment that 'Yeah, it shouldn't be able to interact with the main page.' which I took to mean that I shouldn't be able to click on the main screen...

Anyway, all good, can be closed, and thanks!

**Closed** 2021-07-29 10:06 UTC
